CREATE TABLE Duo (
	Spotify_username VARCHAR(255) NOT NULL,
	name_duo VARCHAR (255) NOT NULL,
	PRIMARY KEY (Spotify_username),
	CONSTRAINT FK_spotify_username_duo FOREIGN KEY Spotify_username
	REFERENCES User_Data(Spotify_username)
);

insert into Duo (Spotify_username, name_duo) values ('fernaldi21', 'Star Squad');
insert into Duo (Spotify_username, name_duo) values ('psiney2i', 'Howell, Heidenreich and O''Conner');
insert into Duo (Spotify_username, name_duo) values ('mmanass13', 'Marquardt LLC');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'Hettinger and Sons');
insert into Duo (Spotify_username, name_duo) values ('sscobbie26', 'Blick LLC');
insert into Duo (Spotify_username, name_duo) values ('pnibleyu', 'Hagenes and Sons');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Simonis, Schaefer and Heaney');
insert into Duo (Spotify_username, name_duo) values ('jobrien1q', 'Lockman Inc');
insert into Duo (Spotify_username, name_duo) values ('rcoginp', 'Fisher Inc');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Fadel, Mills and Hane');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Graham-Windler');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Fisher Inc');
insert into Duo (Spotify_username, name_duo) values ('bpray1w', 'Romaguera, Mueller and Gorczany');
insert into Duo (Spotify_username, name_duo) values ('efransinelli2n', 'Kirlin, Zieme and Farrell');
insert into Duo (Spotify_username, name_duo) values ('lbreissan2h', 'Fritsch Group');
insert into Duo (Spotify_username, name_duo) values ('pranscomb2d', 'Funk, McGlynn and Dach');
insert into Duo (Spotify_username, name_duo) values ('eobrogane2j', 'Schamberger-O''Hara');
insert into Duo (Spotify_username, name_duo) values ('ggillaspyo', 'Stoltenberg-Miller');
insert into Duo (Spotify_username, name_duo) values ('dgianotti2u', 'Johns LLC');
insert into Duo (Spotify_username, name_duo) values ('gpanas6', 'Kuphal Group');
insert into Duo (Spotify_username, name_duo) values ('cmitchelson10', 'Leuschke LLC');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Altenwerth Group');
insert into Duo (Spotify_username, name_duo) values ('abeardsall21', 'Nitzsche-Kertzmann');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Dooley and Sons');
insert into Duo (Spotify_username, name_duo) values ('boverstreetm', 'Klocko-Greenholt');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Padberg, Lind and Durgan');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Olson-Koelpin');
insert into Duo (Spotify_username, name_duo) values ('abennisonh', 'Lowe LLC');
insert into Duo (Spotify_username, name_duo) values ('tdrakes8', 'Abbott, Mills and Oberbrunner');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Hirthe LLC');
insert into Duo (Spotify_username, name_duo) values ('whedau2s', 'Skiles-McCullough');
insert into Duo (Spotify_username, name_duo) values ('mdarbishire22', 'Robel LLC');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Bayer-Rogahn');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Heaney LLC');
insert into Duo (Spotify_username, name_duo) values ('dgaudon2m', 'Frami-Rice');
insert into Duo (Spotify_username, name_duo) values ('glain1a', 'Rohan, Corkery and Hartmann');
insert into Duo (Spotify_username, name_duo) values ('mcassells1f', 'Robel LLC');
insert into Duo (Spotify_username, name_duo) values ('pfranck1i', 'Fahey, Blick and Jaskolski');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'O''Connell Inc');
insert into Duo (Spotify_username, name_duo) values ('alew', 'Walter, McKenzie and Kohler');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Dickens, Crooks and Muller');
insert into Duo (Spotify_username, name_duo) values ('ksibbson1', 'Hamill, Herman and Keebler');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Brakus Group');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Gaylord-Hills');
insert into Duo (Spotify_username, name_duo) values ('lmcneill24', 'Nienow Group');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Heller-Howe');
insert into Duo (Spotify_username, name_duo) values ('dgaudon2m', 'Kerluke-Dooley');
insert into Duo (Spotify_username, name_duo) values ('abeardsall21', 'Runolfsdottir, Torp and Trantow');
insert into Duo (Spotify_username, name_duo) values ('fantecki1d', 'Williamson and Sons');
insert into Duo (Spotify_username, name_duo) values ('dcoventona', 'Schaden-Tremblay');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'Howe-Beatty');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Grant Group');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Fadel-Quitzon');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Kerluke, Hettinger and White');
insert into Duo (Spotify_username, name_duo) values ('gmanueley', 'Douglas-Conn');
insert into Duo (Spotify_username, name_duo) values ('statersale1n', 'Rowe, Huel and Ernser');
insert into Duo (Spotify_username, name_duo) values ('ksibbson1', 'Kreiger, Jakubowski and Gerhold');
insert into Duo (Spotify_username, name_duo) values ('dcoventona', 'Okuneva and Sons');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Luettgen-Langosh');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Kihn and Sons');
insert into Duo (Spotify_username, name_duo) values ('jsheather2o', 'Mills and Sons');
insert into Duo (Spotify_username, name_duo) values ('vde2a', 'Emard LLC');
insert into Duo (Spotify_username, name_duo) values ('sdaud1g', 'Robel, Sporer and Shanahan');
insert into Duo (Spotify_username, name_duo) values ('fsemrad1k', 'Bahringer Inc');
insert into Duo (Spotify_username, name_duo) values ('pnibleyu', 'Gibson, Veum and Turcotte');
insert into Duo (Spotify_username, name_duo) values ('dgaudon2m', 'O''Hara and Sons');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'Robel Group');
insert into Duo (Spotify_username, name_duo) values ('mdolling1j', 'Barrows and Sons');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'Schamberger, Wisoky and Padberg');
insert into Duo (Spotify_username, name_duo) values ('abeardsall21', 'Hermiston, Torphy and Heidenreich');
insert into Duo (Spotify_username, name_duo) values ('jliddiatt19', 'McKenzie, Schulist and Bosco');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Hahn and Sons');
insert into Duo (Spotify_username, name_duo) values ('kspon1l', 'Gulgowski, Cummings and Lubowitz');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Considine-Bartoletti');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Mertz-Kemmer');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'Emard, Zulauf and Douglas');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'Wehner-Kerluke');
insert into Duo (Spotify_username, name_duo) values ('statersale1n', 'Bashirian LLC');
insert into Duo (Spotify_username, name_duo) values ('dlamberto2k', 'Schaden-Corwin');
insert into Duo (Spotify_username, name_duo) values ('gtorrecillat', 'Boyer, Schimmel and Hansen');
insert into Duo (Spotify_username, name_duo) values ('gtorrecillat', 'Dooley, Gutmann and Rath');
insert into Duo (Spotify_username, name_duo) values ('glacroix5', 'Hermiston, Considine and Altenwerth');
insert into Duo (Spotify_username, name_duo) values ('ltrebbled', 'Shields LLC');
insert into Duo (Spotify_username, name_duo) values ('ppuckey1h', 'Torphy-Runolfsdottir');
insert into Duo (Spotify_username, name_duo) values ('dlamberto2k', 'Hettinger, Abbott and Bode');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Schiller-Greenfelder');
insert into Duo (Spotify_username, name_duo) values ('lcucinottaj', 'Becker Inc');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Hudson-Marvin');
insert into Duo (Spotify_username, name_duo) values ('mwelman2e', 'O''Conner and Sons');
insert into Duo (Spotify_username, name_duo) values ('ppuckey1h', 'Doyle, Vandervort and Thiel');
insert into Duo (Spotify_username, name_duo) values ('jobrien1q', 'Sipes-Reilly');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'Larkin, Dare and Kutch');
insert into Duo (Spotify_username, name_duo) values ('chaggus1c', 'Powlowski-Cremin');
insert into Duo (Spotify_username, name_duo) values ('asanchiz1s', 'Johnson Inc');
insert into Duo (Spotify_username, name_duo) values ('dcoventona', 'Kirlin-Bergnaum');
insert into Duo (Spotify_username, name_duo) values ('psiney2i', 'Blanda LLC');
insert into Duo (Spotify_username, name_duo) values ('statersale1n', 'Fay-Kulas');
insert into Duo (Spotify_username, name_duo) values ('chaggus1c', 'Zboncak, Koepp and Nienow');
insert into Duo (Spotify_username, name_duo) values ('dlamberto2k', 'Hintz-Bogan');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Gibson and Sons');
insert into Duo (Spotify_username, name_duo) values ('pvousden1o', 'Aufderhar and Sons');
insert into Duo (Spotify_username, name_duo) values ('pnibleyu', 'Abernathy-Schmitt');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Schiller-Haag');
insert into Duo (Spotify_username, name_duo) values ('dhumblestonez', 'Hahn Inc');
insert into Duo (Spotify_username, name_duo) values ('dhumblestonez', 'Welch-Parisian');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Prohaska, Hayes and Cremin');
insert into Duo (Spotify_username, name_duo) values ('gmanueley', 'Botsford Inc');
insert into Duo (Spotify_username, name_duo) values ('dgianotti2u', 'Heaney-Kiehn');
insert into Duo (Spotify_username, name_duo) values ('mmanass13', 'Macejkovic-Schuppe');
insert into Duo (Spotify_username, name_duo) values ('jliddiatt19', 'Morar-Dooley');
insert into Duo (Spotify_username, name_duo) values ('dmcleary2c', 'Bergnaum LLC');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'Brown-Braun');
insert into Duo (Spotify_username, name_duo) values ('hcuerdaq', 'Thompson LLC');
insert into Duo (Spotify_username, name_duo) values ('ngirkel', 'Boehm-Dibbert');
insert into Duo (Spotify_username, name_duo) values ('boverstreetm', 'Smitham Inc');
insert into Duo (Spotify_username, name_duo) values ('tseelerr', 'Denesik, Schowalter and Mayer');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Haley-Lebsack');
insert into Duo (Spotify_username, name_duo) values ('mcassells1f', 'Brakus, Langosh and Will');
insert into Duo (Spotify_username, name_duo) values ('glain1a', 'Anderson, West and Gutkowski');
insert into Duo (Spotify_username, name_duo) values ('ngirkel', 'Stehr Group');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Murazik Group');
insert into Duo (Spotify_username, name_duo) values ('jliddiatt19', 'Gislason, Streich and Brown');
insert into Duo (Spotify_username, name_duo) values ('tdoveston1x', 'Jakubowski, Braun and Klocko');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Abshire, Brown and Goodwin');
insert into Duo (Spotify_username, name_duo) values ('bpray1w', 'McGlynn LLC');
insert into Duo (Spotify_username, name_duo) values ('goddyg', 'Mraz-Bernier');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Cassin-McCullough');
insert into Duo (Spotify_username, name_duo) values ('dgianotti2u', 'Bergnaum-Goldner');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Schoen-Luettgen');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Adams Inc');
insert into Duo (Spotify_username, name_duo) values ('ghastin3', 'Gerhold, Koss and Bosco');
insert into Duo (Spotify_username, name_duo) values ('statersale1n', 'Turcotte LLC');
insert into Duo (Spotify_username, name_duo) values ('tseelerr', 'Will LLC');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Simonis-McGlynn');
insert into Duo (Spotify_username, name_duo) values ('nnorthedge1r', 'Schinner-Reinger');
insert into Duo (Spotify_username, name_duo) values ('zhawkswood2v', 'Hettinger Group');
insert into Duo (Spotify_username, name_duo) values ('hcuerdaq', 'Davis Group');
insert into Duo (Spotify_username, name_duo) values ('nnorthedge1r', 'Jerde-Adams');
insert into Duo (Spotify_username, name_duo) values ('hgrogor29', 'Maggio, Waters and Pfannerstill');
insert into Duo (Spotify_username, name_duo) values ('vde2a', 'Langworth and Sons');
insert into Duo (Spotify_username, name_duo) values ('cmcmickan2b', 'Bartell Inc');
insert into Duo (Spotify_username, name_duo) values ('psiney2i', 'Cormier Group');
insert into Duo (Spotify_username, name_duo) values ('tdoveston1x', 'Morar Inc');
insert into Duo (Spotify_username, name_duo) values ('pnibleyu', 'Morar-Medhurst');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Steuber and Sons');
insert into Duo (Spotify_username, name_duo) values ('lmcneill24', 'Hilpert, Mitchell and Schroeder');
insert into Duo (Spotify_username, name_duo) values ('fgolson12', 'Daugherty and Sons');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Goyette-Cremin');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Senger-Kihn');
insert into Duo (Spotify_username, name_duo) values ('fgolson12', 'Ferry-Shanahan');
insert into Duo (Spotify_username, name_duo) values ('rgallo0', 'Gutmann-White');
insert into Duo (Spotify_username, name_duo) values ('tdoveston1x', 'Hayes-Dach');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Schuster Group');
insert into Duo (Spotify_username, name_duo) values ('vde2a', 'Bode-Ward');
insert into Duo (Spotify_username, name_duo) values ('mmacgarvey1m', 'Rippin Group');
insert into Duo (Spotify_username, name_duo) values ('pnibleyu', 'Romaguera Inc');
insert into Duo (Spotify_username, name_duo) values ('zhawkswood2v', 'Ruecker, Hansen and Durgan');
insert into Duo (Spotify_username, name_duo) values ('goddyg', 'Kub, Green and Hegmann');
insert into Duo (Spotify_username, name_duo) values ('zhawkswood2v', 'Stark-Powlowski');
insert into Duo (Spotify_username, name_duo) values ('rgallo0', 'Wolff, Brekke and Prosacco');
insert into Duo (Spotify_username, name_duo) values ('gpanas6', 'Thompson, Wisozk and Nicolas');
insert into Duo (Spotify_username, name_duo) values ('gpanas6', 'Fay, Spinka and Kuphal');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Turcotte-Rogahn');
insert into Duo (Spotify_username, name_duo) values ('glain1a', 'Romaguera, Bahringer and Larkin');
insert into Duo (Spotify_username, name_duo) values ('mvettore14', 'Schaefer Inc');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Abshire LLC');
insert into Duo (Spotify_username, name_duo) values ('cjervoise2q', 'Cummings, Bruen and Toy');
insert into Duo (Spotify_username, name_duo) values ('gtorrecillat', 'Hartmann Group');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'Lubowitz Inc');
insert into Duo (Spotify_username, name_duo) values ('mvettore14', 'Deckow, Wilkinson and Durgan');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'Volkman and Sons');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'Zboncak, Hermann and Beer');
insert into Duo (Spotify_username, name_duo) values ('dleverentz7', 'Russel Group');
insert into Duo (Spotify_username, name_duo) values ('nnorthedge1r', 'Nikolaus-Wiegand');
insert into Duo (Spotify_username, name_duo) values ('hcuerdaq', 'Smith-Koepp');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Kautzer, Jacobson and Marquardt');
insert into Duo (Spotify_username, name_duo) values ('acuttings1z', 'Larkin Group');
insert into Duo (Spotify_username, name_duo) values ('boverstreetm', 'Johnson-Gorczany');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'McKenzie, Hoppe and Hoeger');
insert into Duo (Spotify_username, name_duo) values ('mmacgarvey1m', 'Halvorson, Marks and Hessel');
insert into Duo (Spotify_username, name_duo) values ('cmccheyne28', 'Davis-O''Conner');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Kemmer LLC');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Johnson Group');
insert into Duo (Spotify_username, name_duo) values ('tseelerr', 'Raynor, Harvey and Kunze');
insert into Duo (Spotify_username, name_duo) values ('ngirkel', 'Larson, O''Keefe and Gibson');
insert into Duo (Spotify_username, name_duo) values ('efransinelli2n', 'Beatty-Jacobi');
insert into Duo (Spotify_username, name_duo) values ('tseelerr', 'Erdman-Hand');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Herzog LLC');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Murray Inc');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'Funk Inc');
insert into Duo (Spotify_username, name_duo) values ('dgianotti2u', 'Christiansen LLC');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Heller LLC');
insert into Duo (Spotify_username, name_duo) values ('gtorrecillat', 'Davis and Sons');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Beahan, Emard and Wiegand');
insert into Duo (Spotify_username, name_duo) values ('dhumblestonez', 'Mitchell, Muller and Howe');
insert into Duo (Spotify_username, name_duo) values ('nshildrick23', 'McGlynn-Ondricka');
insert into Duo (Spotify_username, name_duo) values ('goddyg', 'Heathcote and Sons');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Breitenberg, Prosacco and Will');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Nienow LLC');
insert into Duo (Spotify_username, name_duo) values ('pcrab2r', 'Bahringer, Hand and Satterfield');
insert into Duo (Spotify_username, name_duo) values ('zhawkswood2v', 'Lebsack, Dicki and McGlynn');
insert into Duo (Spotify_username, name_duo) values ('boverstreetm', 'Raynor Group');
insert into Duo (Spotify_username, name_duo) values ('abennisonh', 'Schmitt Group');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Willms, Mueller and Lowe');
insert into Duo (Spotify_username, name_duo) values ('vrasper9', 'Pacocha, Koelpin and Ratke');
insert into Duo (Spotify_username, name_duo) values ('hgrogor29', 'Sauer-Heller');
insert into Duo (Spotify_username, name_duo) values ('fkerseyv', 'Hirthe, Davis and Kautzer');
insert into Duo (Spotify_username, name_duo) values ('nshildrick23', 'Rodriguez-Ward');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Orn-Schaden');
insert into Duo (Spotify_username, name_duo) values ('ghastin3', 'Stehr-Bins');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'Frami, Walker and Kassulke');
insert into Duo (Spotify_username, name_duo) values ('sdaud1g', 'Hilll, Turcotte and Lind');
insert into Duo (Spotify_username, name_duo) values ('cmcmickan2b', 'Rau-Bahringer');
insert into Duo (Spotify_username, name_duo) values ('ucheke2f', 'Schulist and Sons');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Ondricka, Weber and Runolfsdottir');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Orn LLC');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'Runolfsdottir and Sons');
insert into Duo (Spotify_username, name_duo) values ('dhumblestonez', 'Luettgen LLC');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Gulgowski-Jast');
insert into Duo (Spotify_username, name_duo) values ('jsheather2o', 'Bogisich, Heller and Keebler');
insert into Duo (Spotify_username, name_duo) values ('cmcmickan2b', 'Beer, Nicolas and O''Conner');
insert into Duo (Spotify_username, name_duo) values ('hcuerdaq', 'Conn Inc');
insert into Duo (Spotify_username, name_duo) values ('mdolling1j', 'Lindgren Group');
insert into Duo (Spotify_username, name_duo) values ('dcoventona', 'Emmerich, Balistreri and Toy');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Grant-Collins');
insert into Duo (Spotify_username, name_duo) values ('dhallfordc', 'Hoppe-Ward');
insert into Duo (Spotify_username, name_duo) values ('boverstreetm', 'Keeling-O''Connell');
insert into Duo (Spotify_username, name_duo) values ('kspon1l', 'Armstrong-Rau');
insert into Duo (Spotify_username, name_duo) values ('hcuerdaq', 'Hoeger Group');
insert into Duo (Spotify_username, name_duo) values ('statersale1n', 'Feest, Lakin and Wiegand');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'Hammes and Sons');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Ullrich and Sons');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'Becker-Barton');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Pfeffer and Sons');
insert into Duo (Spotify_username, name_duo) values ('pranscomb2d', 'Altenwerth, MacGyver and Adams');
insert into Duo (Spotify_username, name_duo) values ('abeardsall21', 'Orn, Hackett and Hilpert');
insert into Duo (Spotify_username, name_duo) values ('fgolson12', 'Grimes-Green');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'Herzog-Hermann');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Schimmel, Toy and Bernhard');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Witting-Blick');
insert into Duo (Spotify_username, name_duo) values ('ucheke2f', 'Beer and Sons');
insert into Duo (Spotify_username, name_duo) values ('dhumblestonez', 'Brekke Group');
insert into Duo (Spotify_username, name_duo) values ('gtorrecillat', 'Hand, Ebert and Frami');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Murazik, Deckow and Wolf');
insert into Duo (Spotify_username, name_duo) values ('dleverentz7', 'Heller, Balistreri and Kuhlman');
insert into Duo (Spotify_username, name_duo) values ('dmcleary2c', 'Lindgren, Blanda and Pollich');
insert into Duo (Spotify_username, name_duo) values ('fkerseyv', 'Green, Hartmann and Dare');
insert into Duo (Spotify_username, name_duo) values ('ngirkel', 'Stracke and Sons');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Rempel, Botsford and Schumm');
insert into Duo (Spotify_username, name_duo) values ('fkerseyv', 'Corwin and Sons');
insert into Duo (Spotify_username, name_duo) values ('fsemrad1k', 'Rogahn, Hessel and Kuhlman');
insert into Duo (Spotify_username, name_duo) values ('cmccheyne28', 'Tillman-Bernier');
insert into Duo (Spotify_username, name_duo) values ('pnibleyu', 'Reichert-Abbott');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Walter-Crona');
insert into Duo (Spotify_username, name_duo) values ('lmcneill24', 'Schumm-Abshire');
insert into Duo (Spotify_username, name_duo) values ('kspon1l', 'Wiza-Daniel');
insert into Duo (Spotify_username, name_duo) values ('fgolson12', 'Brown, Williamson and Lowe');
insert into Duo (Spotify_username, name_duo) values ('dhallfordc', 'Steuber, Sipes and Rau');
insert into Duo (Spotify_username, name_duo) values ('ghastin3', 'Mante-Ortiz');
insert into Duo (Spotify_username, name_duo) values ('ltrebbled', 'Haley-Abernathy');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Tremblay LLC');
insert into Duo (Spotify_username, name_duo) values ('chaggus1c', 'Dickens-Jacobi');
insert into Duo (Spotify_username, name_duo) values ('fgolson12', 'Lubowitz Group');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Greenholt Group');
insert into Duo (Spotify_username, name_duo) values ('hgrogor29', 'Kulas, Mohr and Stiedemann');
insert into Duo (Spotify_username, name_duo) values ('pranscomb2d', 'Kris, Paucek and Tremblay');
insert into Duo (Spotify_username, name_duo) values ('cmcmickan2b', 'Schneider-Fay');
insert into Duo (Spotify_username, name_duo) values ('alew', 'Boyle LLC');
insert into Duo (Spotify_username, name_duo) values ('statersale1n', 'Little-Gleichner');
insert into Duo (Spotify_username, name_duo) values ('mcassells1f', 'Blanda, Von and Christiansen');
insert into Duo (Spotify_username, name_duo) values ('pvousden1o', 'Kirlin-Borer');
insert into Duo (Spotify_username, name_duo) values ('lbreissan2h', 'Botsford Inc');
insert into Duo (Spotify_username, name_duo) values ('abeardsall21', 'Hauck-Marks');
insert into Duo (Spotify_username, name_duo) values ('dmcleary2c', 'Willms LLC');
insert into Duo (Spotify_username, name_duo) values ('ghastin3', 'Buckridge, Eichmann and Rohan');
insert into Duo (Spotify_username, name_duo) values ('mvettore14', 'Crona-Strosin');
insert into Duo (Spotify_username, name_duo) values ('hcuerdaq', 'Kohler-Macejkovic');
insert into Duo (Spotify_username, name_duo) values ('hgrogor29', 'Stehr, Witting and Lockman');
insert into Duo (Spotify_username, name_duo) values ('tseelerr', 'Parker Inc');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Hills, Bogan and Schaefer');
insert into Duo (Spotify_username, name_duo) values ('mmanass13', 'Lebsack-Quitzon');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Runte Group');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Lebsack, Schultz and Goyette');
insert into Duo (Spotify_username, name_duo) values ('dmcleary2c', 'Tillman, Kemmer and Stroman');
insert into Duo (Spotify_username, name_duo) values ('cmccheyne28', 'Glover, Padberg and Shanahan');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Ryan-Kreiger');
insert into Duo (Spotify_username, name_duo) values ('ggillaspyo', 'Von Group');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Moore and Sons');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Waelchi-Romaguera');
insert into Duo (Spotify_username, name_duo) values ('cmcmickan2b', 'Roberts Group');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'Klein, Ullrich and Barrows');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Wilderman Inc');
insert into Duo (Spotify_username, name_duo) values ('ghastin3', 'VonRueden-Kulas');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Konopelski Group');
insert into Duo (Spotify_username, name_duo) values ('gpanas6', 'Predovic-O''Kon');
insert into Duo (Spotify_username, name_duo) values ('pvousden1o', 'Bogan, Hoeger and Wolff');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Satterfield-Kautzer');
insert into Duo (Spotify_username, name_duo) values ('vde2a', 'Ratke LLC');
insert into Duo (Spotify_username, name_duo) values ('dgianotti2u', 'Rolfson-Schiller');
insert into Duo (Spotify_username, name_duo) values ('tallot16', 'Rice Inc');
insert into Duo (Spotify_username, name_duo) values ('pfranck1i', 'Senger-Larkin');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Glover Group');
insert into Duo (Spotify_username, name_duo) values ('gtorrecillat', 'Johnson and Sons');
insert into Duo (Spotify_username, name_duo) values ('mwelman2e', 'Doyle, Reilly and Feil');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Dickinson, Beier and Reinger');
insert into Duo (Spotify_username, name_duo) values ('pfranck1i', 'Maggio-Windler');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Abbott-Emard');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Schulist-Brekke');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Bode, Herzog and Stiedemann');
insert into Duo (Spotify_username, name_duo) values ('bpray1w', 'Schmeler Inc');
insert into Duo (Spotify_username, name_duo) values ('dhallfordc', 'Kessler, Ondricka and Pfeffer');
insert into Duo (Spotify_username, name_duo) values ('boverstreetm', 'Flatley LLC');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Gerlach Group');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Hermiston-Cole');
insert into Duo (Spotify_username, name_duo) values ('bpray1w', 'Bins-Brakus');
insert into Duo (Spotify_username, name_duo) values ('cjervoise2q', 'White and Sons');
insert into Duo (Spotify_username, name_duo) values ('sscobbie26', 'Wisoky LLC');
insert into Duo (Spotify_username, name_duo) values ('whedau2s', 'Blanda-Cole');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Jacobi, Wisozk and McCullough');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Price, Greenholt and Funk');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Kuhn Group');
insert into Duo (Spotify_username, name_duo) values ('ltrebbled', 'Hettinger LLC');
insert into Duo (Spotify_username, name_duo) values ('whedau2s', 'Cremin Group');
insert into Duo (Spotify_username, name_duo) values ('dleverentz7', 'Raynor, Marquardt and Conroy');
insert into Duo (Spotify_username, name_duo) values ('jobrien1q', 'Wolff, Klocko and Abshire');
insert into Duo (Spotify_username, name_duo) values ('dhallfordc', 'Mohr Group');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Torp, Stokes and Roob');
insert into Duo (Spotify_username, name_duo) values ('vde2a', 'DuBuque Inc');
insert into Duo (Spotify_username, name_duo) values ('lmcneill24', 'Torphy-Boyer');
insert into Duo (Spotify_username, name_duo) values ('ggillaspyo', 'Jakubowski-Kertzmann');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Purdy, Schuster and Cummings');
insert into Duo (Spotify_username, name_duo) values ('zhawkswood2v', 'Medhurst-Wiza');
insert into Duo (Spotify_username, name_duo) values ('cjervoise2q', 'Ebert LLC');
insert into Duo (Spotify_username, name_duo) values ('ggillaspyo', 'Morissette, Von and Bauch');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Legros-Kunze');
insert into Duo (Spotify_username, name_duo) values ('rgallo0', 'Reilly, Hilpert and Terry');
insert into Duo (Spotify_username, name_duo) values ('idellenbroker17', 'O''Hara and Sons');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'Lynch Inc');
insert into Duo (Spotify_username, name_duo) values ('mdarbishire22', 'Kozey, Mohr and Medhurst');
insert into Duo (Spotify_username, name_duo) values ('larnholtz1e', 'Jerde Group');
insert into Duo (Spotify_username, name_duo) values ('cjervoise2q', 'Crist, Thiel and Grimes');
insert into Duo (Spotify_username, name_duo) values ('rcoginp', 'Koch-Ebert');
insert into Duo (Spotify_username, name_duo) values ('dmcleary2c', 'Emmerich-Mayert');
insert into Duo (Spotify_username, name_duo) values ('mdarbishire22', 'Friesen-Nikolaus');
insert into Duo (Spotify_username, name_duo) values ('vde2a', 'Muller-Kshlerin');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'DuBuque-Ullrich');
insert into Duo (Spotify_username, name_duo) values ('mvettore14', 'Rowe and Sons');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'Wilderman, Hyatt and Gorczany');
insert into Duo (Spotify_username, name_duo) values ('gmanueley', 'Collins, Bauch and Schoen');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Nolan, Gerhold and Medhurst');
insert into Duo (Spotify_username, name_duo) values ('pcrab2r', 'Glover-Kessler');
insert into Duo (Spotify_username, name_duo) values ('rgallo0', 'Pacocha LLC');
insert into Duo (Spotify_username, name_duo) values ('ggillaspyo', 'Douglas, Zemlak and Lubowitz');
insert into Duo (Spotify_username, name_duo) values ('dgianotti2u', 'Conroy LLC');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Upton, Bartoletti and Kling');
insert into Duo (Spotify_username, name_duo) values ('ksibbson1', 'Marks-Schmitt');
insert into Duo (Spotify_username, name_duo) values ('chaggus1c', 'Greenholt-Harris');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Lubowitz-Howe');
insert into Duo (Spotify_username, name_duo) values ('fgolson12', 'Windler and Sons');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Mayer, Brekke and Lubowitz');
insert into Duo (Spotify_username, name_duo) values ('mdarbishire22', 'Mueller, Towne and Davis');
insert into Duo (Spotify_username, name_duo) values ('zhawkswood2v', 'Gottlieb-Kuhn');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Kunde Group');
insert into Duo (Spotify_username, name_duo) values ('whedau2s', 'Hudson Group');
insert into Duo (Spotify_username, name_duo) values ('glacroix5', 'Stark LLC');
insert into Duo (Spotify_username, name_duo) values ('idellenbroker17', 'Cormier-Gerhold');
insert into Duo (Spotify_username, name_duo) values ('mdarbishire22', 'Kihn and Sons');
insert into Duo (Spotify_username, name_duo) values ('jsheather2o', 'Boehm, Fahey and Stark');
insert into Duo (Spotify_username, name_duo) values ('ggillaspyo', 'Keeling-Hagenes');
insert into Duo (Spotify_username, name_duo) values ('lbreissan2h', 'Lockman-Gerhold');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Flatley and Sons');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'Kuhic-Goyette');
insert into Duo (Spotify_username, name_duo) values ('ggillaspyo', 'Zemlak, Mueller and Harvey');
insert into Duo (Spotify_username, name_duo) values ('mcassells1f', 'Johnston-Stokes');
insert into Duo (Spotify_username, name_duo) values ('jsheather2o', 'Eichmann-Sauer');
insert into Duo (Spotify_username, name_duo) values ('kurvoy2p', 'Donnelly LLC');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Kihn, Champlin and D''Amore');
insert into Duo (Spotify_username, name_duo) values ('mmanass13', 'Dare, Schinner and Shields');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Turcotte-Corwin');
insert into Duo (Spotify_username, name_duo) values ('bstanyforthe', 'Fritsch, Schumm and Cruickshank');
insert into Duo (Spotify_username, name_duo) values ('dleverentz7', 'Hammes, Deckow and Roob');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'Schiller-Moen');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Torphy Inc');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'McGlynn Group');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Rippin and Sons');
insert into Duo (Spotify_username, name_duo) values ('lbreissan2h', 'Reynolds LLC');
insert into Duo (Spotify_username, name_duo) values ('pvousden1o', 'Schoen LLC');
insert into Duo (Spotify_username, name_duo) values ('pranscomb2d', 'Kautzer and Sons');
insert into Duo (Spotify_username, name_duo) values ('nshildrick23', 'Powlowski-Boyer');
insert into Duo (Spotify_username, name_duo) values ('gmanueley', 'Heller-Daugherty');
insert into Duo (Spotify_username, name_duo) values ('rcoginp', 'Breitenberg-Schmeler');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Kautzer, Mertz and Sauer');
insert into Duo (Spotify_username, name_duo) values ('lcucinottaj', 'Gottlieb Group');
insert into Duo (Spotify_username, name_duo) values ('mvettore14', 'Moen Inc');
insert into Duo (Spotify_username, name_duo) values ('ghastin3', 'Carter LLC');
insert into Duo (Spotify_username, name_duo) values ('mdolling1j', 'McDermott-Graham');
insert into Duo (Spotify_username, name_duo) values ('pfranck1i', 'Kirlin-Murazik');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'McKenzie Inc');
insert into Duo (Spotify_username, name_duo) values ('vrasper9', 'Rodriguez Inc');
insert into Duo (Spotify_username, name_duo) values ('acuttings1z', 'Orn, Gorczany and Gleichner');
insert into Duo (Spotify_username, name_duo) values ('bpray1w', 'Langosh Inc');
insert into Duo (Spotify_username, name_duo) values ('dgaudon2m', 'Walter-Adams');
insert into Duo (Spotify_username, name_duo) values ('dhallfordc', 'Pfeffer Inc');
insert into Duo (Spotify_username, name_duo) values ('cpelchatk', 'Jast-Jenkins');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Hoeger LLC');
insert into Duo (Spotify_username, name_duo) values ('bstanyforthe', 'Schuppe-Walter');
insert into Duo (Spotify_username, name_duo) values ('dhumblestonez', 'Dibbert Inc');
insert into Duo (Spotify_username, name_duo) values ('dleverentz7', 'Simonis-Rodriguez');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Tromp Group');
insert into Duo (Spotify_username, name_duo) values ('jsheather2o', 'Tremblay LLC');
insert into Duo (Spotify_username, name_duo) values ('abennisonh', 'Smitham LLC');
insert into Duo (Spotify_username, name_duo) values ('tseelerr', 'Kiehn-Frami');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Bailey, Haley and Walsh');
insert into Duo (Spotify_username, name_duo) values ('whedau2s', 'Gleichner, Hodkiewicz and Mertz');
insert into Duo (Spotify_username, name_duo) values ('mwelman2e', 'Hahn, Mann and Dooley');
insert into Duo (Spotify_username, name_duo) values ('hgrogor29', 'Stanton Inc');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Lockman-Prosacco');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Kulas Inc');
insert into Duo (Spotify_username, name_duo) values ('ghastin3', 'Lynch, Prohaska and Daniel');
insert into Duo (Spotify_username, name_duo) values ('mvettore14', 'Robel-Marvin');
insert into Duo (Spotify_username, name_duo) values ('mvettore14', 'Johns-Tromp');
insert into Duo (Spotify_username, name_duo) values ('tdoveston1x', 'Lebsack-White');
insert into Duo (Spotify_username, name_duo) values ('cmitchelson10', 'Hickle-Heller');
insert into Duo (Spotify_username, name_duo) values ('ngirkel', 'Kihn and Sons');
insert into Duo (Spotify_username, name_duo) values ('jsheather2o', 'Becker-Roberts');
insert into Duo (Spotify_username, name_duo) values ('jobrien1q', 'Cummerata LLC');
insert into Duo (Spotify_username, name_duo) values ('hgrogor29', 'Block Group');
insert into Duo (Spotify_username, name_duo) values ('lmcneill24', 'Dietrich, Hagenes and Conn');
insert into Duo (Spotify_username, name_duo) values ('pfranck1i', 'McLaughlin-McGlynn');
insert into Duo (Spotify_username, name_duo) values ('cmcmickan2b', 'Frami-Stokes');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Connelly Group');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'Erdman, Boyer and Feest');
insert into Duo (Spotify_username, name_duo) values ('dlamberto2k', 'Stanton-Aufderhar');
insert into Duo (Spotify_username, name_duo) values ('abeardsall21', 'Wuckert LLC');
insert into Duo (Spotify_username, name_duo) values ('efransinelli2n', 'Heaney-Goodwin');
insert into Duo (Spotify_username, name_duo) values ('ltrebbled', 'Tromp-Turner');
insert into Duo (Spotify_username, name_duo) values ('alew', 'Pagac-Ryan');
insert into Duo (Spotify_username, name_duo) values ('cpelchatk', 'Kerluke, Williamson and Ryan');
insert into Duo (Spotify_username, name_duo) values ('goddyg', 'Johnston LLC');
insert into Duo (Spotify_username, name_duo) values ('dlamberto2k', 'Hodkiewicz Inc');
insert into Duo (Spotify_username, name_duo) values ('psiney2i', 'Koepp, Harber and Lind');
insert into Duo (Spotify_username, name_duo) values ('rcoginp', 'Hickle, Parisian and Padberg');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Monahan Inc');
insert into Duo (Spotify_username, name_duo) values ('boverstreetm', 'Jast-Luettgen');
insert into Duo (Spotify_username, name_duo) values ('ltrebbled', 'Reichert, Thiel and Bartell');
insert into Duo (Spotify_username, name_duo) values ('pvousden1o', 'Gleason Inc');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Keeling-Howe');
insert into Duo (Spotify_username, name_duo) values ('dhumblestonez', 'Cruickshank, Crist and Hackett');
insert into Duo (Spotify_username, name_duo) values ('chaggus1c', 'MacGyver LLC');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Cormier, Shanahan and Bailey');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Jacobi, Durgan and Kihn');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Rippin-Franecki');
insert into Duo (Spotify_username, name_duo) values ('abennisonh', 'Powlowski LLC');
insert into Duo (Spotify_username, name_duo) values ('vde2a', 'Bergnaum, Gusikowski and Welch');
insert into Duo (Spotify_username, name_duo) values ('mdolling1j', 'Frami and Sons');
insert into Duo (Spotify_username, name_duo) values ('dgaudon2m', 'Hammes-Hansen');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Walsh-Kautzer');
insert into Duo (Spotify_username, name_duo) values ('cpelchatk', 'Barton-Hickle');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Rath-Lang');
insert into Duo (Spotify_username, name_duo) values ('mcassells1f', 'Jast-Stanton');
insert into Duo (Spotify_username, name_duo) values ('ggillaspyo', 'Quigley-Reilly');
insert into Duo (Spotify_username, name_duo) values ('tdrakes8', 'Senger LLC');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Kris Group');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Johnston, Gulgowski and Wiegand');
insert into Duo (Spotify_username, name_duo) values ('rgallo0', 'Mosciski, Nitzsche and Bogan');
insert into Duo (Spotify_username, name_duo) values ('dleverentz7', 'Maggio, Auer and Graham');
insert into Duo (Spotify_username, name_duo) values ('larnholtz1e', 'Hudson and Sons');
insert into Duo (Spotify_username, name_duo) values ('gmanueley', 'Hoeger-Sporer');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Murphy LLC');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Hickle-Gleason');
insert into Duo (Spotify_username, name_duo) values ('gtorrecillat', 'Pouros Inc');
insert into Duo (Spotify_username, name_duo) values ('nshildrick23', 'Tillman-Rogahn');
insert into Duo (Spotify_username, name_duo) values ('mbompas27', 'Leuschke, Jacobi and Emard');
insert into Duo (Spotify_username, name_duo) values ('abeardsall21', 'Dickinson and Sons');
insert into Duo (Spotify_username, name_duo) values ('hgrogor29', 'Kemmer, Lebsack and McLaughlin');
insert into Duo (Spotify_username, name_duo) values ('ucheke2f', 'Durgan, O''Conner and Ledner');
insert into Duo (Spotify_username, name_duo) values ('ucheke2f', 'Brown and Sons');
insert into Duo (Spotify_username, name_duo) values ('rcoginp', 'Hane, Walter and Goyette');
insert into Duo (Spotify_username, name_duo) values ('pcrab2r', 'Kuhic-Kuhn');
insert into Duo (Spotify_username, name_duo) values ('pnibleyu', 'Abernathy LLC');
insert into Duo (Spotify_username, name_duo) values ('pnibleyu', 'Ullrich-Bechtelar');
insert into Duo (Spotify_username, name_duo) values ('mcassells1f', 'Kub, Stiedemann and O''Keefe');
insert into Duo (Spotify_username, name_duo) values ('ltrebbled', 'Herman-Hickle');
insert into Duo (Spotify_username, name_duo) values ('sdaud1g', 'McLaughlin, Hirthe and Ratke');
insert into Duo (Spotify_username, name_duo) values ('lcucinottaj', 'Schiller LLC');
insert into Duo (Spotify_username, name_duo) values ('ksibbson1', 'Ledner-Olson');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Kshlerin LLC');
insert into Duo (Spotify_username, name_duo) values ('pvousden1o', 'Rutherford LLC');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Crooks, McClure and Gaylord');
insert into Duo (Spotify_username, name_duo) values ('larnholtz1e', 'Skiles LLC');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Breitenberg-Heaney');
insert into Duo (Spotify_username, name_duo) values ('mbompas27', 'Little and Sons');
insert into Duo (Spotify_username, name_duo) values ('fsemrad1k', 'Kuhlman, Kessler and Bosco');
insert into Duo (Spotify_username, name_duo) values ('rgallo0', 'Batz-Turcotte');
insert into Duo (Spotify_username, name_duo) values ('cworthy2g', 'Littel and Sons');
insert into Duo (Spotify_username, name_duo) values ('rgallo0', 'Wolf-Schowalter');
insert into Duo (Spotify_username, name_duo) values ('asanchiz1s', 'Cummings, Kihn and Thiel');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Vandervort-Parisian');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Watsica, Dare and Yundt');
insert into Duo (Spotify_username, name_duo) values ('glacroix5', 'Lehner-Beer');
insert into Duo (Spotify_username, name_duo) values ('abeardsall21', 'Mraz LLC');
insert into Duo (Spotify_username, name_duo) values ('dleverentz7', 'Lockman-Farrell');
insert into Duo (Spotify_username, name_duo) values ('efransinelli2n', 'Macejkovic-Ruecker');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Daugherty, Miller and Carter');
insert into Duo (Spotify_username, name_duo) values ('dhallfordc', 'Sporer, Crist and Feil');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Green-Osinski');
insert into Duo (Spotify_username, name_duo) values ('dmcleary2c', 'Feest-O''Connell');
insert into Duo (Spotify_username, name_duo) values ('goddyg', 'Rempel, Koelpin and Beatty');
insert into Duo (Spotify_username, name_duo) values ('gpanas6', 'Walter LLC');
insert into Duo (Spotify_username, name_duo) values ('jobrien1q', 'Olson, Hodkiewicz and O''Keefe');
insert into Duo (Spotify_username, name_duo) values ('eobrogane2j', 'Emard-Blick');
insert into Duo (Spotify_username, name_duo) values ('cmitchelson10', 'Barton-Moen');
insert into Duo (Spotify_username, name_duo) values ('abeardsall21', 'Wolf Group');
insert into Duo (Spotify_username, name_duo) values ('idellenbroker17', 'Breitenberg LLC');
insert into Duo (Spotify_username, name_duo) values ('alew', 'Daniel, Block and Goodwin');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Shields-Schaden');
insert into Duo (Spotify_username, name_duo) values ('lmcneill24', 'Osinski LLC');
insert into Duo (Spotify_username, name_duo) values ('dgaudon2m', 'Marquardt, Dicki and Emmerich');
insert into Duo (Spotify_username, name_duo) values ('abennisonh', 'Abernathy-Abernathy');
insert into Duo (Spotify_username, name_duo) values ('glacroix5', 'Rowe LLC');
insert into Duo (Spotify_username, name_duo) values ('cjervoise2q', 'Jacobi, Wilderman and Lubowitz');
insert into Duo (Spotify_username, name_duo) values ('lcucinottaj', 'Bosco-Wiza');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'VonRueden-Hansen');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Streich-Rice');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Deckow Inc');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Jenkins-Gaylord');
insert into Duo (Spotify_username, name_duo) values ('ggillaspyo', 'Stokes, Marquardt and Dare');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Wuckert, Reichel and Gaylord');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Bergstrom, Robel and Koch');
insert into Duo (Spotify_username, name_duo) values ('vde2a', 'Block LLC');
insert into Duo (Spotify_username, name_duo) values ('bpray1w', 'McCullough-Hahn');
insert into Duo (Spotify_username, name_duo) values ('ksibbson1', 'Bauch Group');
insert into Duo (Spotify_username, name_duo) values ('sscobbie26', 'Bechtelar Inc');
insert into Duo (Spotify_username, name_duo) values ('cworthy2g', 'Hyatt-Reichel');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Adams Group');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Goldner, Gibson and Barton');
insert into Duo (Spotify_username, name_duo) values ('gmanueley', 'Abbott-Langosh');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Deckow, Bruen and Ratke');
insert into Duo (Spotify_username, name_duo) values ('fgolson12', 'Leannon-Stokes');
insert into Duo (Spotify_username, name_duo) values ('lmcneill24', 'Schulist Inc');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Halvorson, Mohr and Tillman');
insert into Duo (Spotify_username, name_duo) values ('pranscomb2d', 'Graham-Fahey');
insert into Duo (Spotify_username, name_duo) values ('ucheke2f', 'Hilpert Group');
insert into Duo (Spotify_username, name_duo) values ('dhumblestonez', 'DuBuque-Konopelski');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Conn LLC');
insert into Duo (Spotify_username, name_duo) values ('whedau2s', 'Wintheiser, Carter and VonRueden');
insert into Duo (Spotify_username, name_duo) values ('tseelerr', 'Miller, Walter and Fritsch');
insert into Duo (Spotify_username, name_duo) values ('mmacgarvey1m', 'Thiel-Goldner');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Jakubowski-Kozey');
insert into Duo (Spotify_username, name_duo) values ('lbreissan2h', 'MacGyver-Huels');
insert into Duo (Spotify_username, name_duo) values ('glain1a', 'Wehner Group');
insert into Duo (Spotify_username, name_duo) values ('cmccheyne28', 'Jones, Herman and Rempel');
insert into Duo (Spotify_username, name_duo) values ('mcassells1f', 'Jerde and Sons');
insert into Duo (Spotify_username, name_duo) values ('ltrebbled', 'Pfannerstill LLC');
insert into Duo (Spotify_username, name_duo) values ('pvousden1o', 'Williamson-Hackett');
insert into Duo (Spotify_username, name_duo) values ('ngirkel', 'O''Hara Inc');
insert into Duo (Spotify_username, name_duo) values ('pnibleyu', 'Ankunding-Kub');
insert into Duo (Spotify_username, name_duo) values ('ltrebbled', 'Kihn-McLaughlin');
insert into Duo (Spotify_username, name_duo) values ('acuttings1z', 'Walter-Fahey');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Hand LLC');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Jacobi Group');
insert into Duo (Spotify_username, name_duo) values ('sdaud1g', 'Gulgowski, Hammes and O''Kon');
insert into Duo (Spotify_username, name_duo) values ('jsheather2o', 'Robel, Block and Bauch');
insert into Duo (Spotify_username, name_duo) values ('cpelchatk', 'Pagac-Abbott');
insert into Duo (Spotify_username, name_duo) values ('alew', 'Mills-Keebler');
insert into Duo (Spotify_username, name_duo) values ('asanchiz1s', 'Kreiger Inc');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Smitham LLC');
insert into Duo (Spotify_username, name_duo) values ('cmccheyne28', 'Halvorson LLC');
insert into Duo (Spotify_username, name_duo) values ('eobrogane2j', 'Funk LLC');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'Veum Inc');
insert into Duo (Spotify_username, name_duo) values ('mbompas27', 'Mayert-Hauck');
insert into Duo (Spotify_username, name_duo) values ('sdaud1g', 'Crooks, Zemlak and McGlynn');
insert into Duo (Spotify_username, name_duo) values ('hgrogor29', 'Satterfield-Roob');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'Barrows and Sons');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Renner Group');
insert into Duo (Spotify_username, name_duo) values ('acuttings1z', 'Williamson Inc');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'Streich-Stracke');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Block, Howe and Nienow');
insert into Duo (Spotify_username, name_duo) values ('efransinelli2n', 'Bayer-West');
insert into Duo (Spotify_username, name_duo) values ('cmccheyne28', 'Vandervort and Sons');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Batz, Walter and Heaney');
insert into Duo (Spotify_username, name_duo) values ('mdolling1j', 'Wunsch Group');
insert into Duo (Spotify_username, name_duo) values ('vde2a', 'Wilderman, Cartwright and Williamson');
insert into Duo (Spotify_username, name_duo) values ('swindibank11', 'Bernier LLC');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Stanton, Reilly and Rath');
insert into Duo (Spotify_username, name_duo) values ('nshildrick23', 'Balistreri Group');
insert into Duo (Spotify_username, name_duo) values ('hcuerdaq', 'Schultz Inc');
insert into Duo (Spotify_username, name_duo) values ('hcuerdaq', 'Kilback Inc');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Gutkowski-Beahan');
insert into Duo (Spotify_username, name_duo) values ('dlamberto2k', 'Bartell, Hane and Schroeder');
insert into Duo (Spotify_username, name_duo) values ('pranscomb2d', 'Koelpin Inc');
insert into Duo (Spotify_username, name_duo) values ('dmcleary2c', 'O''Hara, Ryan and Labadie');
insert into Duo (Spotify_username, name_duo) values ('ppuckey1h', 'Dickens and Sons');
insert into Duo (Spotify_username, name_duo) values ('tseelerr', 'Jacobson-Vandervort');
insert into Duo (Spotify_username, name_duo) values ('tallot16', 'Effertz and Sons');
insert into Duo (Spotify_username, name_duo) values ('dgaudon2m', 'Wehner, Balistreri and Lind');
insert into Duo (Spotify_username, name_duo) values ('dhumblestonez', 'Stracke-Gottlieb');
insert into Duo (Spotify_username, name_duo) values ('statersale1n', 'McClure-Hessel');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Baumbach, Roob and Witting');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Gleason, Skiles and Fadel');
insert into Duo (Spotify_username, name_duo) values ('ltrebbled', 'Dietrich Inc');
insert into Duo (Spotify_username, name_duo) values ('goddyg', 'Kassulke and Sons');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Balistreri-Okuneva');
insert into Duo (Spotify_username, name_duo) values ('abennisonh', 'Schoen-Heaney');
insert into Duo (Spotify_username, name_duo) values ('sscobbie26', 'Zboncak-King');
insert into Duo (Spotify_username, name_duo) values ('rcoginp', 'Weber and Sons');
insert into Duo (Spotify_username, name_duo) values ('nshildrick23', 'Aufderhar LLC');
insert into Duo (Spotify_username, name_duo) values ('larnholtz1e', 'Zemlak Inc');
insert into Duo (Spotify_username, name_duo) values ('cmccheyne28', 'Mraz, Schmitt and Langworth');
insert into Duo (Spotify_username, name_duo) values ('ggillaspyo', 'Heller-DuBuque');
insert into Duo (Spotify_username, name_duo) values ('mmanass13', 'Price-Hartmann');
insert into Duo (Spotify_username, name_duo) values ('cmitchelson10', 'Dietrich Group');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Wiegand and Sons');
insert into Duo (Spotify_username, name_duo) values ('dgaudon2m', 'O''Conner-Carroll');
insert into Duo (Spotify_username, name_duo) values ('vde2a', 'Douglas-Torp');
insert into Duo (Spotify_username, name_duo) values ('cjervoise2q', 'Waters, Lebsack and Carroll');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Greenfelder-Hahn');
insert into Duo (Spotify_username, name_duo) values ('mcassells1f', 'Bechtelar, Greenfelder and Veum');
insert into Duo (Spotify_username, name_duo) values ('bstanyforthe', 'Bode-Raynor');
insert into Duo (Spotify_username, name_duo) values ('acuttings1z', 'Lang, McDermott and Walker');
insert into Duo (Spotify_username, name_duo) values ('cpelchatk', 'Stanton Inc');
insert into Duo (Spotify_username, name_duo) values ('sscobbie26', 'Ritchie-Ledner');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Ferry, Wiegand and Gottlieb');
insert into Duo (Spotify_username, name_duo) values ('ltrebbled', 'Klein Group');
insert into Duo (Spotify_username, name_duo) values ('fkerseyv', 'Labadie-Erdman');
insert into Duo (Spotify_username, name_duo) values ('lmcneill24', 'Fahey-Spinka');
insert into Duo (Spotify_username, name_duo) values ('dgaudon2m', 'Brakus, Bogisich and Nitzsche');
insert into Duo (Spotify_username, name_duo) values ('pcrab2r', 'Pollich-Yost');
insert into Duo (Spotify_username, name_duo) values ('ucheke2f', 'Steuber, Glover and Hackett');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Moen, VonRueden and Stracke');
insert into Duo (Spotify_username, name_duo) values ('chaggus1c', 'Mayer-Johnston');
insert into Duo (Spotify_username, name_duo) values ('larnholtz1e', 'O''Reilly, O''Keefe and Gleason');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Champlin LLC');
insert into Duo (Spotify_username, name_duo) values ('ucheke2f', 'Kertzmann-O''Reilly');
insert into Duo (Spotify_username, name_duo) values ('dcoventona', 'Gibson Inc');
insert into Duo (Spotify_username, name_duo) values ('fantecki1d', 'Leuschke, Dooley and Spinka');
insert into Duo (Spotify_username, name_duo) values ('ucheke2f', 'Gutkowski and Sons');
insert into Duo (Spotify_username, name_duo) values ('dcoventona', 'Goldner, Dooley and Heaney');
insert into Duo (Spotify_username, name_duo) values ('statersale1n', 'Bednar, MacGyver and Schiller');
insert into Duo (Spotify_username, name_duo) values ('tallot16', 'Hackett-Lesch');
insert into Duo (Spotify_username, name_duo) values ('lbreissan2h', 'Bode Group');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'Stehr, Satterfield and Wolf');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'Bednar, Conroy and Koelpin');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Miller-Feeney');
insert into Duo (Spotify_username, name_duo) values ('dgaudon2m', 'Cruickshank, McKenzie and Hintz');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Runolfsdottir, Kris and Feeney');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'Simonis-Kohler');
insert into Duo (Spotify_username, name_duo) values ('boverstreetm', 'Prosacco, Wolff and Frami');
insert into Duo (Spotify_username, name_duo) values ('bstanyforthe', 'Deckow-O''Conner');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Gleason Group');
insert into Duo (Spotify_username, name_duo) values ('bstanyforthe', 'Abernathy Group');
insert into Duo (Spotify_username, name_duo) values ('lmcneill24', 'O''Conner-Muller');
insert into Duo (Spotify_username, name_duo) values ('vde2a', 'D''Amore LLC');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Langworth Group');
insert into Duo (Spotify_username, name_duo) values ('dlamberto2k', 'Rohan, Fritsch and Schuster');
insert into Duo (Spotify_username, name_duo) values ('abeardsall21', 'Mann, Ferry and Kuphal');
insert into Duo (Spotify_username, name_duo) values ('dcoventona', 'Brekke and Sons');
insert into Duo (Spotify_username, name_duo) values ('gpanas6', 'Brown-Bailey');
insert into Duo (Spotify_username, name_duo) values ('mmacgarvey1m', 'Turner-Wyman');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Prohaska Group');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'Green Inc');
insert into Duo (Spotify_username, name_duo) values ('vde2a', 'Glover-Dare');
insert into Duo (Spotify_username, name_duo) values ('mwelman2e', 'Marquardt, Okuneva and Goodwin');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Leuschke-Johns');
insert into Duo (Spotify_username, name_duo) values ('hgrogor29', 'Kessler-Miller');
insert into Duo (Spotify_username, name_duo) values ('ngirkel', 'Johnson, Shanahan and Rutherford');
insert into Duo (Spotify_username, name_duo) values ('chaggus1c', 'Leuschke Inc');
insert into Duo (Spotify_username, name_duo) values ('fsemrad1k', 'Bartell and Sons');
insert into Duo (Spotify_username, name_duo) values ('mbompas27', 'Emmerich, Ullrich and Willms');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Bednar, Mayert and Torp');
insert into Duo (Spotify_username, name_duo) values ('ngirkel', 'Kozey, Stanton and Stamm');
insert into Duo (Spotify_username, name_duo) values ('bpray1w', 'Schultz-Runte');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'Schmeler Group');
insert into Duo (Spotify_username, name_duo) values ('fgolson12', 'Miller, Boehm and Raynor');
insert into Duo (Spotify_username, name_duo) values ('dleverentz7', 'Anderson Group');
insert into Duo (Spotify_username, name_duo) values ('mdarbishire22', 'Harris, Ward and Goldner');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Mertz-Boehm');
insert into Duo (Spotify_username, name_duo) values ('ucheke2f', 'Howe-Prohaska');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Klocko and Sons');
insert into Duo (Spotify_username, name_duo) values ('tdrakes8', 'Haley, Feeney and Connelly');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'McGlynn, O''Kon and McGlynn');
insert into Duo (Spotify_username, name_duo) values ('larnholtz1e', 'Spencer Inc');
insert into Duo (Spotify_username, name_duo) values ('fkerseyv', 'Mraz Inc');
insert into Duo (Spotify_username, name_duo) values ('dhumblestonez', 'Kirlin LLC');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'Rogahn, Lueilwitz and Hoppe');
insert into Duo (Spotify_username, name_duo) values ('vrasper9', 'Wiza Group');
insert into Duo (Spotify_username, name_duo) values ('chaggus1c', 'Hahn, Wyman and Wilderman');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Swaniawski LLC');
insert into Duo (Spotify_username, name_duo) values ('ucheke2f', 'Stracke, Schaefer and Hickle');
insert into Duo (Spotify_username, name_duo) values ('kspon1l', 'Farrell-Grant');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Christiansen-Dare');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'Lockman-Stark');
insert into Duo (Spotify_username, name_duo) values ('kurvoy2p', 'Ebert-Bergnaum');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Corwin, Von and Watsica');
insert into Duo (Spotify_username, name_duo) values ('glacroix5', 'Wilkinson-Huel');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Smitham-Stokes');
insert into Duo (Spotify_username, name_duo) values ('ngirkel', 'McCullough Group');
insert into Duo (Spotify_username, name_duo) values ('ajapp2l', 'Goyette-Beier');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Hickle-Little');
insert into Duo (Spotify_username, name_duo) values ('pvousden1o', 'Ankunding Inc');
insert into Duo (Spotify_username, name_duo) values ('fsemrad1k', 'Hauck LLC');
insert into Duo (Spotify_username, name_duo) values ('bpray1w', 'Pfannerstill LLC');
insert into Duo (Spotify_username, name_duo) values ('abennisonh', 'Denesik, Von and Durgan');
insert into Duo (Spotify_username, name_duo) values ('fgolson12', 'Stehr LLC');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'Green, Batz and Champlin');
insert into Duo (Spotify_username, name_duo) values ('jliddiatt19', 'Braun Inc');
insert into Duo (Spotify_username, name_duo) values ('pranscomb2d', 'Friesen, Johnston and Murphy');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Johnson-Weimann');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Greenfelder and Sons');
insert into Duo (Spotify_username, name_duo) values ('tseelerr', 'Boyle and Sons');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Yundt, Reinger and Murphy');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Hoppe-Treutel');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Huels, Spinka and Langworth');
insert into Duo (Spotify_username, name_duo) values ('fkerseyv', 'Denesik Inc');
insert into Duo (Spotify_username, name_duo) values ('jliddiatt19', 'Hilpert and Sons');
insert into Duo (Spotify_username, name_duo) values ('gtorrecillat', 'Mann Inc');
insert into Duo (Spotify_username, name_duo) values ('mbompas27', 'Simonis, Friesen and Luettgen');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Hoppe-Ortiz');
insert into Duo (Spotify_username, name_duo) values ('ksibbson1', 'Ziemann, Lesch and Hagenes');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Herman LLC');
insert into Duo (Spotify_username, name_duo) values ('glacroix5', 'Cummings and Sons');
insert into Duo (Spotify_username, name_duo) values ('goddyg', 'Baumbach, Greenfelder and Hegmann');
insert into Duo (Spotify_username, name_duo) values ('gpanas6', 'Schuppe and Sons');
insert into Duo (Spotify_username, name_duo) values ('abeardsall21', 'Lowe Group');
insert into Duo (Spotify_username, name_duo) values ('cjervoise2q', 'Runte-Jakubowski');
insert into Duo (Spotify_username, name_duo) values ('bcitrine1u', 'Howe-Schamberger');
insert into Duo (Spotify_username, name_duo) values ('rgallo0', 'Quigley Inc');
insert into Duo (Spotify_username, name_duo) values ('mmacgarvey1m', 'Skiles-Heidenreich');
insert into Duo (Spotify_username, name_duo) values ('boverstreetm', 'Moen-Abbott');
insert into Duo (Spotify_username, name_duo) values ('swindibank11', 'Hagenes-Rogahn');
insert into Duo (Spotify_username, name_duo) values ('lbreissan2h', 'Brekke and Sons');
insert into Duo (Spotify_username, name_duo) values ('mdarbishire22', 'Schneider, Gorczany and Kozey');
insert into Duo (Spotify_username, name_duo) values ('gpanas6', 'Kirlin, Cummerata and Dietrich');
insert into Duo (Spotify_username, name_duo) values ('ucheke2f', 'Ziemann-Greenholt');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Adams-Wolf');
insert into Duo (Spotify_username, name_duo) values ('lcucinottaj', 'Nitzsche LLC');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'Dicki, Mueller and Kub');
insert into Duo (Spotify_username, name_duo) values ('tallot16', 'Stokes, Reichert and Fritsch');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Beer, Mohr and Sporer');
insert into Duo (Spotify_username, name_duo) values ('tdrakes8', 'Boehm, Carroll and Kuphal');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Kuphal LLC');
insert into Duo (Spotify_username, name_duo) values ('jsheather2o', 'Satterfield-Tromp');
insert into Duo (Spotify_username, name_duo) values ('rcoginp', 'Hermiston-McGlynn');
insert into Duo (Spotify_username, name_duo) values ('tdrakes8', 'Koch, Pfannerstill and Bernhard');
insert into Duo (Spotify_username, name_duo) values ('cmitchelson10', 'Ortiz, Keebler and Kuhlman');
insert into Duo (Spotify_username, name_duo) values ('jliddiatt19', 'Toy-Little');
insert into Duo (Spotify_username, name_duo) values ('pfranck1i', 'Koch and Sons');
insert into Duo (Spotify_username, name_duo) values ('mbompas27', 'Weissnat, Auer and Kozey');
insert into Duo (Spotify_username, name_duo) values ('ghastin3', 'Cummerata and Sons');
insert into Duo (Spotify_username, name_duo) values ('kurvoy2p', 'Bailey LLC');
insert into Duo (Spotify_username, name_duo) values ('cmcmickan2b', 'Turcotte-Corwin');
insert into Duo (Spotify_username, name_duo) values ('ngirkel', 'Morissette Group');
insert into Duo (Spotify_username, name_duo) values ('gpanas6', 'Parker Inc');
insert into Duo (Spotify_username, name_duo) values ('cmccheyne28', 'Rau-Mraz');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Olson, Schimmel and Ritchie');
insert into Duo (Spotify_username, name_duo) values ('pfranck1i', 'Hermann, Kiehn and Deckow');
insert into Duo (Spotify_username, name_duo) values ('cmitchelson10', 'Stark, Mertz and Osinski');
insert into Duo (Spotify_username, name_duo) values ('ksibbson1', 'Adams, Kling and Hilll');
insert into Duo (Spotify_username, name_duo) values ('chaggus1c', 'O''Keefe, Kris and Legros');
insert into Duo (Spotify_username, name_duo) values ('bstanyforthe', 'Runolfsdottir Group');
insert into Duo (Spotify_username, name_duo) values ('efransinelli2n', 'Russel and Sons');
insert into Duo (Spotify_username, name_duo) values ('fgolson12', 'Heidenreich, Labadie and Nikolaus');
insert into Duo (Spotify_username, name_duo) values ('nshildrick23', 'Streich Inc');
insert into Duo (Spotify_username, name_duo) values ('glain1a', 'Kuphal-Goyette');
insert into Duo (Spotify_username, name_duo) values ('tallot16', 'Predovic-Grady');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Nitzsche-Baumbach');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Dibbert-Hoppe');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Feeney-West');
insert into Duo (Spotify_username, name_duo) values ('dmcleary2c', 'Howe Group');
insert into Duo (Spotify_username, name_duo) values ('jobrien1q', 'Feest and Sons');
insert into Duo (Spotify_username, name_duo) values ('fkerseyv', 'Thompson LLC');
insert into Duo (Spotify_username, name_duo) values ('nnorthedge1r', 'Bayer, Schowalter and Stamm');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'Huel-Turner');
insert into Duo (Spotify_username, name_duo) values ('dmcleary2c', 'Barrows Group');
insert into Duo (Spotify_username, name_duo) values ('tallot16', 'Pouros-Kassulke');
insert into Duo (Spotify_username, name_duo) values ('mdarbishire22', 'Schaden-Durgan');
insert into Duo (Spotify_username, name_duo) values ('pfranck1i', 'Strosin LLC');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'King, Schultz and Ritchie');
insert into Duo (Spotify_username, name_duo) values ('goddyg', 'Nienow-Balistreri');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Schuster Group');
insert into Duo (Spotify_username, name_duo) values ('bstanyforthe', 'Doyle, Reynolds and Spinka');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Franecki, Abernathy and Cummerata');
insert into Duo (Spotify_username, name_duo) values ('tseelerr', 'Russel, Kautzer and Towne');
insert into Duo (Spotify_username, name_duo) values ('hgrogor29', 'Vandervort-Mayer');
insert into Duo (Spotify_username, name_duo) values ('lmcneill24', 'O''Conner-Oberbrunner');
insert into Duo (Spotify_username, name_duo) values ('larnholtz1e', 'Paucek LLC');
insert into Duo (Spotify_username, name_duo) values ('tallot16', 'Jerde Inc');
insert into Duo (Spotify_username, name_duo) values ('efransinelli2n', 'Balistreri, Fadel and Rempel');
insert into Duo (Spotify_username, name_duo) values ('alew', 'Ortiz LLC');
insert into Duo (Spotify_username, name_duo) values ('ksibbson1', 'Marvin and Sons');
insert into Duo (Spotify_username, name_duo) values ('psiney2i', 'Cummings-Hauck');
insert into Duo (Spotify_username, name_duo) values ('pfranck1i', 'Lemke-Erdman');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'Ferry and Sons');
insert into Duo (Spotify_username, name_duo) values ('dgianotti2u', 'Buckridge, Cremin and Bergstrom');
insert into Duo (Spotify_username, name_duo) values ('rcoginp', 'Weber and Sons');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'Zboncak, Runolfsson and DuBuque');
insert into Duo (Spotify_username, name_duo) values ('pvousden1o', 'Murphy-Zemlak');
insert into Duo (Spotify_username, name_duo) values ('mbompas27', 'Sawayn, McGlynn and Hoppe');
insert into Duo (Spotify_username, name_duo) values ('cweekly2', 'Yundt, Kuphal and Grant');
insert into Duo (Spotify_username, name_duo) values ('nshildrick23', 'Morissette, Heidenreich and Batz');
insert into Duo (Spotify_username, name_duo) values ('pfranck1i', 'Crooks-Blick');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Sauer Group');
insert into Duo (Spotify_username, name_duo) values ('gmanueley', 'Little-Medhurst');
insert into Duo (Spotify_username, name_duo) values ('rgallo0', 'O''Conner-Nikolaus');
insert into Duo (Spotify_username, name_duo) values ('abennisonh', 'Welch-Cremin');
insert into Duo (Spotify_username, name_duo) values ('swindibank11', 'Krajcik Inc');
insert into Duo (Spotify_username, name_duo) values ('idellenbroker17', 'Harber, Blick and Carroll');
insert into Duo (Spotify_username, name_duo) values ('bstanyforthe', 'Gibson LLC');
insert into Duo (Spotify_username, name_duo) values ('cmcmickan2b', 'Muller Inc');
insert into Duo (Spotify_username, name_duo) values ('bpray1w', 'Cassin, Olson and Wintheiser');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Lockman, Hand and Stracke');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Gusikowski LLC');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Buckridge, Greenholt and Deckow');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'Runolfsson, Kulas and Ruecker');
insert into Duo (Spotify_username, name_duo) values ('kurvoy2p', 'Hegmann Inc');
insert into Duo (Spotify_username, name_duo) values ('fsemrad1k', 'Reinger and Sons');
insert into Duo (Spotify_username, name_duo) values ('whedau2s', 'Kling, Grimes and Senger');
insert into Duo (Spotify_username, name_duo) values ('cmcmickan2b', 'Towne, Vandervort and Renner');
insert into Duo (Spotify_username, name_duo) values ('jliddiatt19', 'Wyman-Cormier');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Collier, Bins and Breitenberg');
insert into Duo (Spotify_username, name_duo) values ('mvettore14', 'Murphy, Ritchie and Cummings');
insert into Duo (Spotify_username, name_duo) values ('mwelman2e', 'Ortiz-Schmidt');
insert into Duo (Spotify_username, name_duo) values ('alew', 'Erdman, King and Bartell');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'Hilll, Ritchie and Dicki');
insert into Duo (Spotify_username, name_duo) values ('larnholtz1e', 'Ziemann-Conroy');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Botsford-Rodriguez');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Shields LLC');
insert into Duo (Spotify_username, name_duo) values ('ajapp2l', 'Beier-Purdy');
insert into Duo (Spotify_username, name_duo) values ('ngirkel', 'Beatty, Runolfsson and Bartoletti');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Cartwright-Kris');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Kohler LLC');
insert into Duo (Spotify_username, name_duo) values ('cworthy2g', 'Rutherford-Kertzmann');
insert into Duo (Spotify_username, name_duo) values ('cpelchatk', 'Reynolds-Wolf');
insert into Duo (Spotify_username, name_duo) values ('efransinelli2n', 'Conn, Mertz and Heidenreich');
insert into Duo (Spotify_username, name_duo) values ('dcoventona', 'Feest-Kutch');
insert into Duo (Spotify_username, name_duo) values ('alew', 'Monahan Inc');
insert into Duo (Spotify_username, name_duo) values ('sscobbie26', 'Harris, Roob and Bergstrom');
insert into Duo (Spotify_username, name_duo) values ('kurvoy2p', 'Stiedemann-Sanford');
insert into Duo (Spotify_username, name_duo) values ('asanchiz1s', 'Glover-Thiel');
insert into Duo (Spotify_username, name_duo) values ('dhallfordc', 'Goyette-Jacobs');
insert into Duo (Spotify_username, name_duo) values ('hgrogor29', 'Krajcik Group');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Bechtelar-Jones');
insert into Duo (Spotify_username, name_duo) values ('alew', 'Gleichner LLC');
insert into Duo (Spotify_username, name_duo) values ('cmcmickan2b', 'McCullough Inc');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Satterfield-Hauck');
insert into Duo (Spotify_username, name_duo) values ('fkerseyv', 'Schaefer-Waters');
insert into Duo (Spotify_username, name_duo) values ('rgallo0', 'Bosco-Hickle');
insert into Duo (Spotify_username, name_duo) values ('mdolling1j', 'Swift and Sons');
insert into Duo (Spotify_username, name_duo) values ('dhumblestonez', 'Sanford, Haag and Swift');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Pacocha-Kreiger');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'Reichel-Schinner');
insert into Duo (Spotify_username, name_duo) values ('jliddiatt19', 'Pfannerstill-Considine');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Kassulke and Sons');
insert into Duo (Spotify_username, name_duo) values ('cmitchelson10', 'Bartell, Hayes and Schmidt');
insert into Duo (Spotify_username, name_duo) values ('pcrab2r', 'Brekke LLC');
insert into Duo (Spotify_username, name_duo) values ('mwelman2e', 'Wolf Inc');
insert into Duo (Spotify_username, name_duo) values ('friggott20', 'Beer-Terry');
insert into Duo (Spotify_username, name_duo) values ('acuttings1z', 'Fay-Jakubowski');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Stanton-Jenkins');
insert into Duo (Spotify_username, name_duo) values ('efransinelli2n', 'Labadie-Pfeffer');
insert into Duo (Spotify_username, name_duo) values ('mmanass13', 'Hahn Inc');
insert into Duo (Spotify_username, name_duo) values ('fkerseyv', 'Herzog, Gottlieb and Wehner');
insert into Duo (Spotify_username, name_duo) values ('fkerseyv', 'Considine and Sons');
insert into Duo (Spotify_username, name_duo) values ('pcrab2r', 'Gibson, Satterfield and Turcotte');
insert into Duo (Spotify_username, name_duo) values ('bstanyforthe', 'Wilkinson, Nader and Ebert');
insert into Duo (Spotify_username, name_duo) values ('gmanueley', 'Runte LLC');
insert into Duo (Spotify_username, name_duo) values ('jobrien1q', 'Hermann and Sons');
insert into Duo (Spotify_username, name_duo) values ('pnibleyu', 'Schmeler LLC');
insert into Duo (Spotify_username, name_duo) values ('nshildrick23', 'O''Kon-Hermann');
insert into Duo (Spotify_username, name_duo) values ('mbompas27', 'Bogan LLC');
insert into Duo (Spotify_username, name_duo) values ('acuttings1z', 'Reichel, Rippin and Dickinson');
insert into Duo (Spotify_username, name_duo) values ('dleverentz7', 'Wehner, Bernhard and Marquardt');
insert into Duo (Spotify_username, name_duo) values ('jromainb', 'Bogisich, Ullrich and Steuber');
insert into Duo (Spotify_username, name_duo) values ('eobrogane2j', 'Kunze, Howe and Daniel');
insert into Duo (Spotify_username, name_duo) values ('zhawkswood2v', 'Hauck-Abernathy');
insert into Duo (Spotify_username, name_duo) values ('rcoginp', 'Balistreri LLC');
insert into Duo (Spotify_username, name_duo) values ('mmanass13', 'Stracke-Maggio');
insert into Duo (Spotify_username, name_duo) values ('pvousden1o', 'Durgan Inc');
insert into Duo (Spotify_username, name_duo) values ('mmanass13', 'West Inc');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Bahringer-Dach');
insert into Duo (Spotify_username, name_duo) values ('pranscomb2d', 'West LLC');
insert into Duo (Spotify_username, name_duo) values ('glacroix5', 'Hane Group');
insert into Duo (Spotify_username, name_duo) values ('mfortoun1t', 'Herman, Nienow and Satterfield');
insert into Duo (Spotify_username, name_duo) values ('boverstreetm', 'Greenfelder Inc');
insert into Duo (Spotify_username, name_duo) values ('idellenbroker17', 'Kuhlman-Bashirian');
insert into Duo (Spotify_username, name_duo) values ('egraysmarkn', 'Moore-Beier');
insert into Duo (Spotify_username, name_duo) values ('chaggus1c', 'Volkman-Huel');
insert into Duo (Spotify_username, name_duo) values ('mdarbishire22', 'Wuckert-Kunze');
insert into Duo (Spotify_username, name_duo) values ('fsemrad1k', 'Miller-Rippin');
insert into Duo (Spotify_username, name_duo) values ('dhumblestonez', 'Sanford, Kerluke and Lebsack');
insert into Duo (Spotify_username, name_duo) values ('psiney2i', 'Turner, Fritsch and Adams');
insert into Duo (Spotify_username, name_duo) values ('vrasper9', 'Rempel, Corwin and Bergnaum');
insert into Duo (Spotify_username, name_duo) values ('tallot16', 'Cummings Inc');
insert into Duo (Spotify_username, name_duo) values ('cjervoise2q', 'Mueller, Cremin and Turcotte');
insert into Duo (Spotify_username, name_duo) values ('cworthy2g', 'Gaylord Inc');
insert into Duo (Spotify_username, name_duo) values ('bstanyforthe', 'Schumm, Pouros and Wilkinson');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Reilly-Hayes');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Bins, Heidenreich and Pagac');
insert into Duo (Spotify_username, name_duo) values ('mdarbishire22', 'Fahey, Lueilwitz and Pollich');
insert into Duo (Spotify_username, name_duo) values ('goddyg', 'Bergnaum, Weber and Considine');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'DuBuque-Schmitt');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Bergstrom and Sons');
insert into Duo (Spotify_username, name_duo) values ('fgolson12', 'Langosh-Metz');
insert into Duo (Spotify_username, name_duo) values ('cworthy2g', 'Bradtke Group');
insert into Duo (Spotify_username, name_duo) values ('alanmeids', 'Mertz Inc');
insert into Duo (Spotify_username, name_duo) values ('ksibbson1', 'Price-Pfeffer');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Kessler, Hilll and Lebsack');
insert into Duo (Spotify_username, name_duo) values ('asanchiz1s', 'Gottlieb Group');
insert into Duo (Spotify_username, name_duo) values ('tdoveston1x', 'Ziemann, Ondricka and Bogisich');
insert into Duo (Spotify_username, name_duo) values ('bstanyforthe', 'Ernser Inc');
insert into Duo (Spotify_username, name_duo) values ('jmangin25', 'Little and Sons');
insert into Duo (Spotify_username, name_duo) values ('gpanas6', 'Boyer Group');
insert into Duo (Spotify_username, name_duo) values ('tseelerr', 'Wiza, Rau and Homenick');
insert into Duo (Spotify_username, name_duo) values ('vrasper9', 'D''Amore-Stamm');
insert into Duo (Spotify_username, name_duo) values ('dmcleary2c', 'Walsh, O''Connell and Nicolas');
insert into Duo (Spotify_username, name_duo) values ('jsheather2o', 'Hickle-Klein');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Hoppe and Sons');
insert into Duo (Spotify_username, name_duo) values ('cmitchelson10', 'Trantow LLC');
insert into Duo (Spotify_username, name_duo) values ('larnholtz1e', 'Rolfson LLC');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Osinski, VonRueden and Reichel');
insert into Duo (Spotify_username, name_duo) values ('tseelerr', 'Weber-Altenwerth');
insert into Duo (Spotify_username, name_duo) values ('zhawkswood2v', 'Gutkowski, Carroll and Corkery');
insert into Duo (Spotify_username, name_duo) values ('lmcneill24', 'Cremin-Runolfsson');
insert into Duo (Spotify_username, name_duo) values ('ksibbson1', 'Olson, Kreiger and Heaney');
insert into Duo (Spotify_username, name_duo) values ('mdolling1j', 'Schumm-Doyle');
insert into Duo (Spotify_username, name_duo) values ('dleverentz7', 'Harris-Morissette');
insert into Duo (Spotify_username, name_duo) values ('lgue1b', 'Christiansen, Rippin and Ledner');
insert into Duo (Spotify_username, name_duo) values ('lcucinottaj', 'Hane, Schimmel and Harvey');
insert into Duo (Spotify_username, name_duo) values ('mwelman2e', 'Lowe Inc');
insert into Duo (Spotify_username, name_duo) values ('tdrakes8', 'West-Kunze');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Howe Group');
insert into Duo (Spotify_username, name_duo) values ('dmcleary2c', 'Sawayn-Schowalter');
insert into Duo (Spotify_username, name_duo) values ('abeardsall21', 'Prosacco LLC');
insert into Duo (Spotify_username, name_duo) values ('whedau2s', 'Sanford, Bergnaum and Doyle');
insert into Duo (Spotify_username, name_duo) values ('fantecki1d', 'Keebler LLC');
insert into Duo (Spotify_username, name_duo) values ('kurvoy2p', 'Wilkinson, Zemlak and Beahan');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Langworth, Kreiger and Koss');
insert into Duo (Spotify_username, name_duo) values ('mdarbishire22', 'Marvin-Hagenes');
insert into Duo (Spotify_username, name_duo) values ('fantecki1d', 'Funk and Sons');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'Collier LLC');
insert into Duo (Spotify_username, name_duo) values ('rgallo0', 'Satterfield-Stark');
insert into Duo (Spotify_username, name_duo) values ('nshildrick23', 'Wiza, Stroman and Schmeler');
insert into Duo (Spotify_username, name_duo) values ('nshildrick23', 'Welch LLC');
insert into Duo (Spotify_username, name_duo) values ('rcoginp', 'Schroeder, Baumbach and Wintheiser');
insert into Duo (Spotify_username, name_duo) values ('cmccheyne28', 'Lemke Group');
insert into Duo (Spotify_username, name_duo) values ('mmanass13', 'Boyer-Witting');
insert into Duo (Spotify_username, name_duo) values ('tprobyn1y', 'Adams-Gutkowski');
insert into Duo (Spotify_username, name_duo) values ('boverstreetm', 'O''Connell Group');
insert into Duo (Spotify_username, name_duo) values ('ghastin3', 'Langworth and Sons');
insert into Duo (Spotify_username, name_duo) values ('rgallo0', 'Jaskolski Inc');
insert into Duo (Spotify_username, name_duo) values ('goddyg', 'Cronin-Swift');
insert into Duo (Spotify_username, name_duo) values ('hgrogor29', 'Jacobs and Sons');
insert into Duo (Spotify_username, name_duo) values ('larnholtz1e', 'Spinka Group');
insert into Duo (Spotify_username, name_duo) values ('efransinelli2n', 'Gleichner-Jakubowski');
insert into Duo (Spotify_username, name_duo) values ('dcoventona', 'Bradtke-Emard');
insert into Duo (Spotify_username, name_duo) values ('ltrebbled', 'Kutch and Sons');
insert into Duo (Spotify_username, name_duo) values ('fchiswell4', 'Hills, Nikolaus and Blanda');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Jaskolski LLC');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Rau Group');
insert into Duo (Spotify_username, name_duo) values ('sgoatman2t', 'Botsford Inc');
insert into Duo (Spotify_username, name_duo) values ('cmitchelson10', 'Brakus Inc');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Batz and Sons');
insert into Duo (Spotify_username, name_duo) values ('mmacgarvey1m', 'Sawayn, Farrell and Heaney');
insert into Duo (Spotify_username, name_duo) values ('jspurmani', 'Pollich, O''Keefe and Gulgowski');
insert into Duo (Spotify_username, name_duo) values ('tdoveston1x', 'Kunde and Sons');
insert into Duo (Spotify_username, name_duo) values ('rcoginp', 'Howell-Parisian');
insert into Duo (Spotify_username, name_duo) values ('mmacgarvey1m', 'Leannon Inc');
insert into Duo (Spotify_username, name_duo) values ('tdoveston1x', 'Rodriguez-Gaylord');
insert into Duo (Spotify_username, name_duo) values ('cmcmickan2b', 'Wilderman-Keebler');
insert into Duo (Spotify_username, name_duo) values ('mdarbishire22', 'Stracke-Johns');
insert into Duo (Spotify_username, name_duo) values ('tdoveston1x', 'Gusikowski-Cummerata');
insert into Duo (Spotify_username, name_duo) values ('mvettore14', 'Bernier-Kub');
insert into Duo (Spotify_username, name_duo) values ('abennisonh', 'Kihn-Wiza');
insert into Duo (Spotify_username, name_duo) values ('boverstreetm', 'Conroy, Okuneva and Crona');
insert into Duo (Spotify_username, name_duo) values ('lbreissan2h', 'Swaniawski Group');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'Auer Inc');
insert into Duo (Spotify_username, name_duo) values ('jkingcote1v', 'Stoltenberg Inc');
insert into Duo (Spotify_username, name_duo) values ('cjervoise2q', 'Wolf-Hagenes');
insert into Duo (Spotify_username, name_duo) values ('fsemrad1k', 'Cremin-Buckridge');
insert into Duo (Spotify_username, name_duo) values ('abridief', 'Lueilwitz Group');
insert into Duo (Spotify_username, name_duo) values ('gtorrecillat', 'Turcotte Inc');
insert into Duo (Spotify_username, name_duo) values ('npinnigar1p', 'Kassulke-Tillman');
insert into Duo (Spotify_username, name_duo) values ('cjervoise2q', 'Rice-Bosco');
insert into Duo (Spotify_username, name_duo) values ('mwelman2e', 'Rowe, Hermann and Rippin');
insert into Duo (Spotify_username, name_duo) values ('dgunx', 'Kuvalis, Schiller and Herzog');
insert into Duo (Spotify_username, name_duo) values ('ppuckey1h', 'Stroman and Sons');
insert into Duo (Spotify_username, name_duo) values ('ajapp2l', 'Rau-Gerlach');
insert into Duo (Spotify_username, name_duo) values ('glacroix5', 'Champlin, Kohler and Bosco');
insert into Duo (Spotify_username, name_duo) values ('ghastin3', 'Keebler-Swift');
insert into Duo (Spotify_username, name_duo) values ('alew', 'West, Hartmann and West');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'O''Conner, Hickle and Runolfsdottir');
insert into Duo (Spotify_username, name_duo) values ('lmcneill24', 'Will LLC');
insert into Duo (Spotify_username, name_duo) values ('ppuckey1h', 'Cronin Inc');
insert into Duo (Spotify_username, name_duo) values ('nnorthedge1r', 'Weimann-Howe');
insert into Duo (Spotify_username, name_duo) values ('mmanass13', 'Heller, Champlin and Feeney');
insert into Duo (Spotify_username, name_duo) values ('dmcleary2c', 'Schamberger Inc');
insert into Duo (Spotify_username, name_duo) values ('dhallfordc', 'Murazik Group');
insert into Duo (Spotify_username, name_duo) values ('mbachellier18', 'Legros and Sons');
insert into Duo (Spotify_username, name_duo) values ('ajapp2l', 'Zieme, DuBuque and Hahn');
insert into Duo (Spotify_username, name_duo) values ('mroose15', 'Dietrich, Schimmel and Feeney');
insert into Duo (Spotify_username, name_duo) values ('alew', 'Emmerich, Nicolas and Jerde');
