CREATE TABLE Duo (
	Spotify_username VARCHAR(16) NOT NULL,
	name_duo VARCHAR (255) NOT NULL,
	PRIMARY KEY (Spotify_username),
	CONSTRAINT FK_spotify_username_duo FOREIGN KEY (Spotify_username)
	REFERENCES User_Data(Spotify_username)
);

insert into Duo (Spotify_username, name_duo) values ('fernaldi21', 'Star Squad');
insert into Duo (Spotify_username, name_duo) values ('bmardall0', 'Toy, Lowe and McCullough');
insert into Duo (Spotify_username, name_duo) values ('kmcgloughlin1', 'Emard LLC');
insert into Duo (Spotify_username, name_duo) values ('odudbridge2', 'Koch Inc');
insert into Duo (Spotify_username, name_duo) values ('rgoncaves3', 'Bradtke Group');
insert into Duo (Spotify_username, name_duo) values ('vakker4', 'MacGyver Inc');
insert into Duo (Spotify_username, name_duo) values ('rfarrington5', 'Bruen, Block and Murphy');
insert into Duo (Spotify_username, name_duo) values ('sriglesford6', 'Rutherford-Turcotte');
insert into Duo (Spotify_username, name_duo) values ('mhandsheart7', 'Runte-Kozey');
insert into Duo (Spotify_username, name_duo) values ('bparlatt8', 'Monahan and Sons');
insert into Duo (Spotify_username, name_duo) values ('fsimonson9', 'Rippin, Schultz and Beatty');
insert into Duo (Spotify_username, name_duo) values ('lbrunia', 'Roberts, Auer and Mante');
insert into Duo (Spotify_username, name_duo) values ('dgierkeb', 'Walter Group');
insert into Duo (Spotify_username, name_duo) values ('bwoodhallc', 'Bahringer-Schmidt');
insert into Duo (Spotify_username, name_duo) values ('egawthorped', 'Moen-Kuvalis');
insert into Duo (Spotify_username, name_duo) values ('lovene', 'Mills, Lind and Marvin');
insert into Duo (Spotify_username, name_duo) values ('kclemsonf', 'Hermann and Sons');
insert into Duo (Spotify_username, name_duo) values ('cfrosdickg', 'Upton Group');
insert into Duo (Spotify_username, name_duo) values ('gpattingtonh', 'Kris, Stoltenberg and McClure');
insert into Duo (Spotify_username, name_duo) values ('sgovieri', 'Williamson-Gleason');
insert into Duo (Spotify_username, name_duo) values ('ghudspithj', 'Schuster Group');
insert into Duo (Spotify_username, name_duo) values ('gpienk', 'Legros Group');
insert into Duo (Spotify_username, name_duo) values ('mkoppell', 'Mante, Fritsch and Donnelly');
insert into Duo (Spotify_username, name_duo) values ('oloudianm', 'Barrows-Ratke');
insert into Duo (Spotify_username, name_duo) values ('glonginan', 'Block-Bernier');
insert into Duo (Spotify_username, name_duo) values ('ezoucho', 'Lynch-Tromp');
insert into Duo (Spotify_username, name_duo) values ('echateletp', 'Kuvalis-Skiles');
insert into Duo (Spotify_username, name_duo) values ('jpoynterq', 'Leuschke-Bradtke');
insert into Duo (Spotify_username, name_duo) values ('amullenr', 'Hansen LLC');
insert into Duo (Spotify_username, name_duo) values ('dtimletts', 'Heller-Pagac');
insert into Duo (Spotify_username, name_duo) values ('mhurrant', 'Reinger, Roob and Stokes');
insert into Duo (Spotify_username, name_duo) values ('pwashbrooku', 'Schamberger LLC');
insert into Duo (Spotify_username, name_duo) values ('fmebiusv', 'Stanton LLC');
insert into Duo (Spotify_username, name_duo) values ('sscripturew', 'Klein Inc');
insert into Duo (Spotify_username, name_duo) values ('ieallisx', 'Bahringer-Mueller');
insert into Duo (Spotify_username, name_duo) values ('chakeworthy', 'Mohr, Eichmann and Reichel');
insert into Duo (Spotify_username, name_duo) values ('gfriesz', 'Nitzsche LLC');
insert into Duo (Spotify_username, name_duo) values ('jkite10', 'Johnson Inc');
insert into Duo (Spotify_username, name_duo) values ('bjailler11', 'Emmerich-Dietrich');
insert into Duo (Spotify_username, name_duo) values ('cpugh12', 'Durgan-Pagac');
insert into Duo (Spotify_username, name_duo) values ('ddake13', 'Franecki, Dare and Wolf');
insert into Duo (Spotify_username, name_duo) values ('bhalahan14', 'Walsh-Sauer');
insert into Duo (Spotify_username, name_duo) values ('ddiviney15', 'Huel, Fritsch and Luettgen');
insert into Duo (Spotify_username, name_duo) values ('msilber16', 'Kuphal-Runolfsson');
insert into Duo (Spotify_username, name_duo) values ('ctimny17', 'Gusikowski, Ledner and Borer');
insert into Duo (Spotify_username, name_duo) values ('eschoffler18', 'Wilderman-Botsford');
insert into Duo (Spotify_username, name_duo) values ('arolls19', 'Thompson-Sawayn');
insert into Duo (Spotify_username, name_duo) values ('lwiseman1a', 'Schuppe, Runolfsson and Lesch');
insert into Duo (Spotify_username, name_duo) values ('gtrahmel1b', 'Ward, Fahey and Towne');
insert into Duo (Spotify_username, name_duo) values ('pjeandon1c', 'Mitchell, Rath and Corkery');
insert into Duo (Spotify_username, name_duo) values ('smcjerrow1d', 'Feil-Raynor');
insert into Duo (Spotify_username, name_duo) values ('palster1e', 'Kemmer-Cruickshank');
insert into Duo (Spotify_username, name_duo) values ('dnarup1f', 'Mohr Group');
insert into Duo (Spotify_username, name_duo) values ('bmazella1g', 'Abshire-Johnson');
insert into Duo (Spotify_username, name_duo) values ('mriall1h', 'Hickle, Konopelski and Lynch');
insert into Duo (Spotify_username, name_duo) values ('tmarrows1i', 'Boehm, Bogisich and Schmidt');
insert into Duo (Spotify_username, name_duo) values ('mtrowler1j', 'Windler Group');
insert into Duo (Spotify_username, name_duo) values ('acutforth1k', 'Kuphal Group');
insert into Duo (Spotify_username, name_duo) values ('awhitrod1l', 'Mitchell, Boehm and Champlin');
insert into Duo (Spotify_username, name_duo) values ('cwallentin1m', 'Heller-Williamson');
insert into Duo (Spotify_username, name_duo) values ('pbarg1n', 'Gerhold and Sons');
insert into Duo (Spotify_username, name_duo) values ('fclerk1o', 'Marks LLC');
insert into Duo (Spotify_username, name_duo) values ('kding1p', 'Torphy-Terry');
insert into Duo (Spotify_username, name_duo) values ('asettle1q', 'Brekke Inc');
insert into Duo (Spotify_username, name_duo) values ('phumblestone1r', 'Kuvalis, Adams and Wolf');
insert into Duo (Spotify_username, name_duo) values ('iarundale1s', 'Barton and Sons');
insert into Duo (Spotify_username, name_duo) values ('bemanulsson1t', 'Rohan LLC');
insert into Duo (Spotify_username, name_duo) values ('bnoyce1u', 'Klein-Fahey');
insert into Duo (Spotify_username, name_duo) values ('eblincko1v', 'Carter-Ratke');
insert into Duo (Spotify_username, name_duo) values ('bdrews1w', 'Kertzmann-Welch');
insert into Duo (Spotify_username, name_duo) values ('sbrunner1x', 'Kub-Pfeffer');
insert into Duo (Spotify_username, name_duo) values ('abouch1y', 'Schneider-Murphy');
insert into Duo (Spotify_username, name_duo) values ('jbaldcock1z', 'Pouros-Keebler');
insert into Duo (Spotify_username, name_duo) values ('ahaddinton20', 'Pollich-Kreiger');
insert into Duo (Spotify_username, name_duo) values ('dhastewell21', 'Corkery LLC');
insert into Duo (Spotify_username, name_duo) values ('rstorer22', 'Kirlin, Collier and Daugherty');
insert into Duo (Spotify_username, name_duo) values ('cgrogor23', 'O''Kon-Hammes');
insert into Duo (Spotify_username, name_duo) values ('hhubber24', 'Kiehn-Jones');
insert into Duo (Spotify_username, name_duo) values ('ssomerscales25', 'Goldner, Thompson and Maggio');
insert into Duo (Spotify_username, name_duo) values ('mgodspede26', 'Stiedemann, Schultz and Ullrich');
insert into Duo (Spotify_username, name_duo) values ('mmartschke27', 'McLaughlin and Sons');
insert into Duo (Spotify_username, name_duo) values ('measterfield28', 'Murphy-Wisoky');
insert into Duo (Spotify_username, name_duo) values ('dcaen29', 'White Inc');
insert into Duo (Spotify_username, name_duo) values ('jswansbury2a', 'Wisoky Group');
insert into Duo (Spotify_username, name_duo) values ('aspadeck2b', 'Jerde-Larson');
insert into Duo (Spotify_username, name_duo) values ('eluke2c', 'Wilderman, Kuhic and Windler');
insert into Duo (Spotify_username, name_duo) values ('aodowne2d', 'Donnelly Inc');
insert into Duo (Spotify_username, name_duo) values ('bbeaman2e', 'Padberg Group');
insert into Duo (Spotify_username, name_duo) values ('phyndley2f', 'Keebler and Sons');
insert into Duo (Spotify_username, name_duo) values ('sshelborne2g', 'Rau LLC');
insert into Duo (Spotify_username, name_duo) values ('ktassell2h', 'Jaskolski, Bins and Tillman');
insert into Duo (Spotify_username, name_duo) values ('tloffill2i', 'Feest LLC');
insert into Duo (Spotify_username, name_duo) values ('bcopins2j', 'Bahringer, Glover and Christiansen');
insert into Duo (Spotify_username, name_duo) values ('bzavattero2k', 'Schiller Group');
insert into Duo (Spotify_username, name_duo) values ('cklulisek2l', 'Jacobson, Kutch and Hammes');
insert into Duo (Spotify_username, name_duo) values ('cpedgrift2m', 'Bergnaum, Lang and Kshlerin');
insert into Duo (Spotify_username, name_duo) values ('lharp2n', 'Kshlerin, Emmerich and Denesik');
insert into Duo (Spotify_username, name_duo) values ('alumsdall2o', 'Sauer, Jenkins and Reinger');
insert into Duo (Spotify_username, name_duo) values ('amundford2p', 'Upton-Larkin');
insert into Duo (Spotify_username, name_duo) values ('sdufore2q', 'Howell LLC');
insert into Duo (Spotify_username, name_duo) values ('mvillaret2r', 'Powlowski-Hagenes');
