CREATE TABLE Family (
	Spotify_username VARCHAR(255) NOT NULL,
	address_family int NOT NULL,
	city_family VARCHAR(255) NOT NULL,
	country_family VARCHAR(255) NOT NULL,
	name_family VARCHAR(255) NOT NULL,
	state_family VARCHAR(255) NOT NULL,
	street_family VARCHAR(255) NOT NULL,
	postal_family int NOT NULL,
	PRIMARY KEY (Spotify_username),
	CONSTRAINT FK_spotify_username_family FOREIGN KEY Spotify_username
	REFERENCES User_Data(Spotify_username)
);

insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('dimas30', '32', 'Bandung', 'Indonesia', 'Sadim', 'Jawa Barat', 'Cisitu', '123456');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('ajuza2s', '02', 'Austin', 'United States', 'Monte Carlo', 'Texas', 'Mcbride', '78764');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('mshirlaw2t', '6', 'Watertown', 'United States', 'Civic', 'Massachusetts', 'Prairieview', '02472');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('silyenko2u', '3', 'Anchorage', 'United States', 'Sentra', 'Alaska', 'Mccormick', '99599');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('vgamwell2v', '37', 'Austin', 'United States', 'LeSabre', 'Texas', 'Cascade', '78721');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('tsteggals2w', '731', 'Chicago', 'United States', 'Defender', 'Illinois', 'Larry', '60663');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('dmcgray2x', '3', 'Vero Beach', 'United States', 'Sidekick', 'Florida', 'Bunker Hill', '32964');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('mtomczykiewicz2y', '7', 'Fayetteville', 'United States', 'G', 'North Carolina', 'Judy', '28305');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('vcassey2z', '7', 'Philadelphia', 'United States', 'Grand Prix', 'Pennsylvania', 'Macpherson', '19151');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('adicker30', '9', 'Clearwater', 'United States', 'Aveo', 'Florida', 'Loeprich', '34620');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('hcostell31', '45', 'Wichita', 'United States', 'Ram 1500 Club', 'Kansas', 'Rigney', '67236');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('gkeyson32', '827', 'Sacramento', 'United States', 'Escort', 'California', 'Dunning', '95833');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('jferie33', '1', 'Orlando', 'United States', 'Z4', 'Florida', 'Beilfuss', '32803');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('bmepham34', '8', 'Fort Worth', 'United States', '626', 'Texas', 'Mccormick', '76178');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('abrake35', '03041', 'Kalamazoo', 'United States', 'Esprit', 'Michigan', 'Hoepker', '49006');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('lpadula36', '97558', 'Newport News', 'United States', 'Starion', 'Virginia', 'Macpherson', '23612');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('nlenard37', '3', 'Seminole', 'United States', 'F250', 'Florida', 'Rusk', '34642');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('vprovis38', '87932', 'Milwaukee', 'United States', 'Taurus', 'Wisconsin', 'Hanson', '53263');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('akenforth39', '50471', 'Loretto', 'United States', 'Sonoma Club Coupe', 'Minnesota', 'Fairview', '55598');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('gdenecamp3a', '82092', 'Miami', 'United States', 'M3', 'Florida', 'Montana', '33164');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('ghallgate3b', '43855', 'Las Vegas', 'United States', 'Elantra', 'Nevada', 'Bashford', '89178');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('vsanders3c', '84630', 'Memphis', 'United States', 'MPV', 'Tennessee', 'Eagle Crest', '38161');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('kbelsey3d', '791', 'Silver Spring', 'United States', 'Sunbird', 'Maryland', 'Del Mar', '20904');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('rdjorvic3e', '14', 'Fort Worth', 'United States', 'B2600', 'Texas', 'Dryden', '76115');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('kyushankin3f', '74012', 'Amarillo', 'United States', 'Lumina', 'Texas', 'Mcguire', '79182');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('apirdy3g', '74347', 'Washington', 'United States', 'MX-5', 'District of Columbia', 'Bartillon', '20414');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('bferreiro3h', '42', 'Muncie', 'United States', 'ES', 'Indiana', 'Summer Ridge', '47306');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('cglowacki3i', '7', 'Brockton', 'United States', 'Rodeo', 'Massachusetts', 'Oriole', '02305');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('lratcliffe3j', '807', 'Denver', 'United States', 'Legacy', 'Colorado', 'Arrowood', '80241');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('lbrimham3k', '1', 'Seattle', 'United States', 'Avalanche', 'Washington', 'Fordem', '98127');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('tcollocott3l', '5', 'Trenton', 'United States', 'Tacoma', 'New Jersey', 'Anderson', '08638');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('ifosdike3m', '75', 'San Jose', 'United States', 'E-Class', 'California', 'Declaration', '95194');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('creinisch3n', '6', 'Omaha', 'United States', 'X-Type', 'Nebraska', 'Lakewood', '68197');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('bseakings3o', '761', 'Pensacola', 'United States', 'Leganza', 'Florida', 'Ridgeview', '32590');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('mcraig3p', '6793', 'Sacramento', 'United States', 'Celica', 'California', 'Schiller', '95818');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('cphippen3q', '83', 'Champaign', 'United States', 'Galant', 'Illinois', 'Pierstorff', '61825');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('nkull3r', '56717', 'Madison', 'United States', 'Rio', 'Wisconsin', 'Golf Course', '53716');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('syurinov3s', '3561', 'Pasadena', 'United States', 'Mark LT', 'California', 'Carey', '91103');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('rallibon3t', '14721', 'Corpus Christi', 'United States', 'Corvette', 'Texas', 'Steensland', '78475');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('hrothert3u', '18', 'Tacoma', 'United States', 'Aerostar', 'Washington', 'Monica', '98464');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('gspiers3v', '4', 'Saint Louis', 'United States', 'G35', 'Missouri', 'Butterfield', '63110');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('fweems3w', '1', 'Pompano Beach', 'United States', 'Prius', 'Florida', 'Canary', '33069');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('jeddowes3x', '7', 'Chicago', 'United States', 'Malibu', 'Illinois', 'Ridgeway', '60657');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('fdillingstone3y', '4', 'Minneapolis', 'United States', 'SC', 'Minnesota', 'Melody', '55436');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('cstanney3z', '3323', 'Chicago', 'United States', 'H2', 'Illinois', 'Rigney', '60646');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('zridgwell40', '42273', 'Fort Lauderdale', 'United States', 'Dakota', 'Florida', 'Reindahl', '33305');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('tpichmann41', '9649', 'Tucson', 'United States', 'Tacoma', 'Arizona', 'Roxbury', '85710');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('cnugent42', '84', 'Syracuse', 'United States', 'Sprinter 2500', 'New York', 'Park Meadow', '13210');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('bhulmes43', '87', 'Lubbock', 'United States', 'G25', 'Texas', 'Pierstorff', '79452');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('aloveland44', '0748', 'Anchorage', 'United States', 'Elantra', 'Alaska', 'Swallow', '99599');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('civic45', '33122', 'Houston', 'United States', 'Prelude', 'Texas', 'Jenna', '77228');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('rdelves46', '570', 'Columbia', 'United States', 'Viper', 'South Carolina', 'Mesta', '29203');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('jshemelt47', '260', 'Washington', 'United States', 'Caprice Classic', 'District of Columbia', 'Northridge', '20414');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('abanat48', '384', 'Virginia Beach', 'United States', 'Cayman', 'Virginia', 'Summit', '23464');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('hpavlenko49', '5', 'Shreveport', 'United States', 'Express 1500', 'Louisiana', 'Gulseth', '71151');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('fpeirpoint4a', '14294', 'Tampa', 'United States', 'Matrix', 'Florida', 'Leroy', '33620');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('rhallen4b', '80438', 'Silver Spring', 'United States', 'Routan', 'Maryland', 'Luster', '20910');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('kgerdes4c', '0855', 'Wilmington', 'United States', 'SRX', 'Delaware', 'Kings', '19805');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('imcpheat4d', '96590', 'Boise', 'United States', 'Sierra 1500', 'Idaho', 'Springs', '83716');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('mmunslow4e', '53', 'Vienna', 'United States', 'Sentra', 'Virginia', 'Main', '22184');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('pstitwell4f', '42', 'Flushing', 'United States', 'Legacy', 'New York', 'Lotheville', '11388');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('lcollacombe4g', '8', 'Tucson', 'United States', 'S2000', 'Arizona', 'Dixon', '85720');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('lphythean4h', '5', 'Dallas', 'United States', 'Legacy', 'Texas', 'Talmadge', '75231');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('dmcleary4i', '628', 'New York City', 'United States', 'Sebring', 'New York', 'High Crossing', '10160');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('kseston4j', '3', 'Arlington', 'United States', 'Taurus X', 'Virginia', 'Melvin', '22212');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('lcanavan4k', '4', 'Saint Joseph', 'United States', 'Mountaineer', 'Missouri', 'Rockefeller', '64504');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('agot4l', '437', 'Great Neck', 'United States', 'Eurovan', 'New York', 'Portage', '11024');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('ebucknell4m', '795', 'Winter Haven', 'United States', '2500', 'Florida', 'La Follette', '33884');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('zleyrroyd4n', '52082', 'Abilene', 'United States', 'B-Series', 'Texas', 'Brickson Park', '79605');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('cpedreschi4o', '0', 'Jamaica', 'United States', 'GTO', 'New York', 'Eliot', '11470');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('fmartinson4p', '7', 'Trenton', 'United States', 'Tahoe', 'New Jersey', 'Loftsgordon', '08608');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('lsillito4q', '32512', 'Van Nuys', 'United States', 'Ram 1500', 'California', 'Cambridge', '91499');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('tgullefant4r', '335', 'Little Rock', 'United States', 'Avalon', 'Arkansas', 'Armistice', '72231');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('mcathenod4s', '72', 'Boca Raton', 'United States', 'Aztek', 'Florida', 'Magdeline', '33499');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('ftilbury4t', '67772', 'Jefferson City', 'United States', 'Diamante', 'Missouri', 'North', '65105');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('rpoznanski4u', '54644', 'El Paso', 'United States', 'Marquis', 'Texas', 'Hanover', '79905');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('mkiely4v', '34464', 'Shawnee Mission', 'United States', 'Malibu', 'Kansas', 'Hoard', '66220');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('cmartinson4w', '7', 'Rochester', 'United States', 'XLR', 'New York', 'Donald', '14639');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('mwaywell4x', '78', 'Boston', 'United States', 'Cutlass Supreme', 'Massachusetts', 'Hagan', '02283');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('sbexon4y', '06734', 'Daytona Beach', 'United States', 'G5', 'Florida', 'Marquette', '32128');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('shurran4z', '6067', 'Flint', 'United States', '300C', 'Michigan', 'Warner', '48550');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('pyakovich50', '05', 'Spokane', 'United States', '2500', 'Washington', '4th', '99252');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('vhansie51', '7', 'Albany', 'United States', 'Concorde', 'New York', 'Thackeray', '12222');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('phousin52', '868', 'New York City', 'United States', 'H1', 'New York', 'Summerview', '10099');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('lnaden53', '4451', 'Miami', 'United States', 'Park Avenue', 'Florida', 'Mendota', '33169');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('btout54', '5', 'Sacramento', 'United States', 'S2000', 'California', 'Kensington', '95894');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('dgilbey55', '204', 'Dayton', 'United States', 'Cherokee', 'Ohio', 'Katie', '45419');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('scajkler56', '2871', 'Winston Salem', 'United States', 'Storm', 'North Carolina', 'Darwin', '27105');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('ccollocott57', '95271', 'Dallas', 'United States', 'LTD Crown Victoria', 'Texas', 'Bowman', '75372');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('esims58', '789', 'Pasadena', 'United States', 'Civic', 'California', 'Harbort', '91131');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('gdumphries59', '695', 'Hollywood', 'United States', '3 Series', 'Florida', 'Montana', '33028');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('nforbear5a', '4', 'Buffalo', 'United States', 'HHR Panel', 'New York', 'Reindahl', '14276');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('oskures5b', '613', 'Bradenton', 'United States', 'S-Class', 'Florida', 'Havey', '34282');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('htedorenko5c', '72', 'Toledo', 'United States', 'Sonoma', 'Ohio', 'Dapin', '43615');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('ktow5d', '3614', 'Saint Paul', 'United States', '400E', 'Minnesota', 'Pennsylvania', '55108');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('crush5e', '48374', 'Charlotte', 'United States', 'STS', 'North Carolina', 'Center', '28235');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('psturton5f', '81', 'Oxnard', 'United States', 'Cooper', 'California', 'Del Sol', '93034');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('prookesby5g', '5', 'Jacksonville', 'United States', 'Corvette', 'Florida', 'Debra', '32259');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('melwyn5h', '42', 'Beaufort', 'United States', 'Savana 2500', 'South Carolina', 'Stuart', '29905');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('kshallcrass5i', '91164', 'New York City', 'United States', 'Bonneville', 'New York', 'Manufacturers', '10045');
insert into Family (Spotify_username, address_family, city_family, country_family, name_family, state_family, street_family, postal_family) values ('mkindell5j', '7', 'Baltimore', 'United States', 'Model T', 'Maryland', 'Dovetail', '21281');
