CREATE TABLE Produces_Podcast (
	Podcast_ID int NOT NULL,
	Artist_ID int NOT NULL,
	PRIMARY KEY (Podcast_ID, Artist_ID),
	CONSTRAINT FK_PodcastID FOREIGN KEY (Podcast_ID) REFERENCES Podcast(Podcast_ID)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT FK_ArtistID FOREIGN KEY (Artist_ID)
	REFERENCES Artist(Artist_ID)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2000', '1000');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2001', '1001');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2002', '1002');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2003', '1003');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2004', '1004');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2005', '1005');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2006', '1006');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2007', '1007');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2008', '1008');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2009', '1009');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2010', '1010');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2011', '1011');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2012', '1012');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2013', '1013');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2014', '1014');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2015', '1015');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2016', '1016');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2017', '1017');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2018', '1018');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2019', '1019');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2020', '1020');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2021', '1021');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2022', '1022');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2023', '1023');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2024', '1024');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2025', '1025');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2026', '1026');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2027', '1027');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2028', '1028');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2029', '1029');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2030', '1030');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2031', '1031');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2032', '1032');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2033', '1033');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2034', '1034');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2035', '1035');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2036', '1036');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2037', '1037');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2038', '1038');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2039', '1039');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2040', '1040');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2041', '1041');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2042', '1042');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2043', '1043');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2044', '1044');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2045', '1045');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2046', '1046');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2047', '1047');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2048', '1048');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2049', '1049');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2050', '1050');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2051', '1051');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2052', '1052');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2053', '1053');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2054', '1054');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2055', '1055');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2056', '1056');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2057', '1057');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2058', '1058');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2059', '1059');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2060', '1060');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2061', '1061');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2062', '1062');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2063', '1063');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2064', '1064');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2065', '1065');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2066', '1066');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2067', '1067');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2068', '1068');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2069', '1069');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2070', '1070');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2071', '1071');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2072', '1072');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2073', '1073');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2074', '1074');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2075', '1075');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2076', '1076');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2077', '1077');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2078', '1078');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2079', '1079');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2080', '1080');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2081', '1081');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2082', '1082');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2083', '1083');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2084', '1084');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2085', '1085');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2086', '1086');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2087', '1087');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2088', '1088');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2089', '1089');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2090', '1090');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2091', '1091');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2092', '1092');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2093', '1093');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2094', '1094');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2095', '1095');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2096', '1096');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2097', '1097');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2098', '1098');
insert into Produces_Podcast (Podcast_ID, Artist_ID) values ('2099', '1099');
