CREATE TABLE Student (
	Spotify_username VARCHAR(255) NOT NULL,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	email_atschool VARCHAR(255) NOT NULL,
	country_school VARCHAR(255) NOT NULL,
	name_school VARCHAR(255) NOT NULL,
	PRIMARY KEY (Spotify_username),
	CONSTRAINT FK_spotify_username_student FOREIGN KEY Spotify_username
	REFERENCES User_Data(Spotify_username)
);

insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('TuanYon', 'Yon', 'Sama', 'TuanYon@gmail.com', 'Indonesia', 'Bandung Institute of Technology');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('kghidelli5k', 'Lief', 'Eliff', 'leliff0@dion.ne.jp', 'Mexico', 'Universidad del Noroeste');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('dcrissil5l', 'Jacky', 'Beat', 'jbeat1@facebook.com', 'China', 'Tianjin Open University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('mwayman5m', 'Deck', 'Goodyer', 'dgoodyer2@technorati.com', 'Portugal', 'Instituto Politécnico de Leiria');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('slabitt5n', 'Mariquilla', 'Pabst', 'mpabst3@yale.edu', 'Indonesia', 'Universitas Negeri Makassar');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('toshesnan5o', 'Deane', 'Gulleford', 'dgulleford4@amazon.co.jp', 'Philippines', 'University of Northern Philippines');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('etremberth5p', 'Keary', 'Skirlin', 'kskirlin5@statcounter.com', 'Croatia', 'University of Pula');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('jpendall5q', 'Amerigo', 'Anning', 'aanning6@omniture.com', 'Japan', 'Wakayama Medical College');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('cselby5r', 'Chiarra', 'Stockhill', 'cstockhill7@psu.edu', 'China', 'Hainan University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('hacutt5s', 'Hunfredo', 'Tinton', 'htinton8@wikia.com', 'Ireland', 'University of Dublin, Trinity College');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('aflasby5t', 'Stacee', 'Durnill', 'sdurnill9@nature.com', 'Indonesia', 'Universitas Pekalongan');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('mdusting5u', 'Dulcine', 'Grigorescu', 'dgrigorescua@cnn.com', 'Netherlands', 'Zuyd University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('kcurnok5v', 'Tera', 'Dooler', 'tdoolerb@hp.com', 'Serbia', 'Megatrend University of Applied Sciences');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('mdougharty5w', 'Jeramey', 'Glencrash', 'jglencrashc@istockphoto.com', 'Thailand', 'Chiang Mai Rajabhat University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('teisak5x', 'Aggy', 'Ferriby', 'aferribyd@hao123.com', 'Thailand', 'Burapha University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('chawsby5y', 'Feodor', 'Kelmere', 'fkelmeree@parallels.com', 'Philippines', 'Cagayan State University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('kneward5z', 'Jarrod', 'Haggerty', 'jhaggertyf@simplemachines.org', 'Finland', 'Turku School of Economics and Business Administration');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('gmeasor60', 'Mireille', 'Kesteven', 'mkesteveng@twitter.com', 'Tajikistan', 'Tajik Agrarian University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('wohenery61', 'Donni', 'Casarini', 'dcasarinih@skype.com', 'Sweden', 'Jönköping University College');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('cwyson62', 'Bobbi', 'Schulke', 'bschulkei@microsoft.com', 'China', 'Dongbei University of Finance And Economics');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('avalerio63', 'Ned', 'Broadbury', 'nbroadburyj@about.me', 'Brazil', 'Faculdade Jaguariúna');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('kcaldes64', 'Neal', 'Baumann', 'nbaumannk@npr.org', 'Philippines', 'Manuel S. Enverga University Foundation');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('jkleinstern65', 'Rebekkah', 'Luke', 'rlukel@cam.ac.uk', 'Indonesia', 'Universitas Ibn Khaldun Bogor');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('rhixson66', 'Julianna', 'Tayler', 'jtaylerm@berkeley.edu', 'Peru', 'Universidad Nacional de San Antonio Abad');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('mhallor67', 'Othilie', 'Lambkin', 'olambkinn@salon.com', 'China', 'Liaoning Normal University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('rbernardo68', 'Hershel', 'Crewther', 'hcrewthero@java.com', 'Yemen', 'University of Modern Sciences');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('jgracey69', 'Karoly', 'McElvogue', 'kmcelvoguep@clickbank.net', 'Ukraine', 'Lviv Polytechnic National University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('mmacmorland6a', 'Ailina', 'Cressey', 'acresseyq@foxnews.com', 'Croatia', 'University of Zagreb');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('itant6b', 'Winnah', 'Mepsted', 'wmepstedr@stumbleupon.com', 'China', 'Zhongshan University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('swhipp6c', 'Neils', 'Perrins', 'nperrinss@google.com', 'China', 'Chongqing Medical University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('dhappert6d', 'Lura', 'Predohl', 'lpredohlt@ox.ac.uk', 'China', 'Harbin Normal University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('abaglan6e', 'Kristal', 'Dalby', 'kdalbyu@reference.com', 'Poland', 'Józef Tyszkiewicz College of Business and Computer Science in Bielsko-Biala');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('agaiger6f', 'Nancy', 'MacTurlough', 'nmacturloughv@cbsnews.com', 'Pakistan', 'Newports Institute of Communication & Economics');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('cdandy6g', 'Carolee', 'Klehyn', 'cklehynw@goo.gl', 'South Korea', 'Kongju National University of Education');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('khulme6h', 'Mayer', 'Downham', 'mdownhamx@nhs.uk', 'Indonesia', 'Politeknik Negeri Jakarta');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('ngergely6i', 'Helaine', 'Plewright', 'hplewrighty@cdbaby.com', 'China', 'Peking University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('lcullnean6j', 'Eula', 'Philippson', 'ephilippsonz@bbc.co.uk', 'Bangladesh', 'Begum Rokeya University, Rangpur');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('kharrington6k', 'Edvard', 'Cauthra', 'ecauthra10@pbs.org', 'Indonesia', 'Universitas Sanata Dharma');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('nhorney6l', 'Moe', 'Cullon', 'mcullon11@bloglines.com', 'Peru', 'Universidad Nacional Agraria La Molina');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('ablood6m', 'Ewan', 'Patinkin', 'epatinkin12@spotify.com', 'China', 'Wuhan University of Hydraulic and Electric Engineering');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('ghanwell6n', 'Emmit', 'Renny', 'erenny13@cbslocal.com', 'Gambia', 'EUCLID University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('eselliman6o', 'Garry', 'Timbs', 'gtimbs14@google.es', 'Philippines', 'Southwestern University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('llamswood6p', 'Rutledge', 'Rebillard', 'rrebillard15@pbs.org', 'China', 'Chongqing Wenli University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('aparkman6q', 'Preston', 'Hegg', 'phegg16@dagondesign.com', 'Philippines', 'New Era University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('ttockell6r', 'Beatriz', 'Baudesson', 'bbaudesson17@redcross.org', 'Palestinian Territory', 'Palestine Polytechnic University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('fcoules6s', 'Viki', 'Gionettitti', 'vgionettitti18@auda.org.au', 'China', 'Henan Univeristy');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('ktargetter6t', 'Cacilia', 'Lambot', 'clambot19@un.org', 'New Zealand', 'University of Waikato');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('lriccione6u', 'Sylas', 'Gisburne', 'sgisburne1a@sun.com', 'Brazil', 'EMESCAM - Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('bklimczak6v', 'Saul', 'Lowder', 'slowder1b@mashable.com', 'Argentina', 'Universidad Nacional de la Patagonia "San Juan Bosco"');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('lhearty6w', 'Cordell', 'Maria', 'cmaria1c@plala.or.jp', 'Argentina', 'Universidad de Buenos Aires');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('pdecruse6x', 'Johny', 'Longhorne', 'jlonghorne1d@umich.edu', 'Thailand', 'Thammasat University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('awickliffe6y', 'Rayna', 'Duffan', 'rduffan1e@latimes.com', 'Indonesia', 'Universitas HKBP Nommensen');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('agoodsell6z', 'Gunter', 'Wastling', 'gwastling1f@army.mil', 'Philippines', 'University of Asia and the Pacific');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('gmandifield70', 'Blake', 'Linham', 'blinham1g@answers.com', 'Poland', 'Pedagogical University of Zielona Gora');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('mcollopy71', 'Hattie', 'Meric', 'hmeric1h@buzzfeed.com', 'China', 'Liaoning University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('dmaskelyne72', 'Rod', 'Hartopp', 'rhartopp1i@hp.com', 'Philippines', 'Central Luzon State University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('jlombardo73', 'Dulcie', 'Pocke', 'dpocke1j@theglobeandmail.com', 'Philippines', 'Mindanao State University - Iligan Institute of Technology');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('jbax74', 'Grete', 'Ormshaw', 'gormshaw1k@adobe.com', 'Czech Republic', 'University of Veterinary and Pharmaceutical Science');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('glearie75', 'Cy', 'Abbotts', 'cabbotts1l@plala.or.jp', 'Russia', 'Bashkir State Medical University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('ekittles76', 'Sorcha', 'Hains', 'shains1m@bigcartel.com', 'Czech Republic', 'University of Education Hradec Kralove');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('jtitchen77', 'Agnella', 'Sproston', 'asproston1n@amazon.com', 'Sweden', 'Stockholm Institute of Education');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('fmathouse78', 'Kerrill', 'Phizackerly', 'kphizackerly1o@baidu.com', 'Somalia', 'Sanaag University of Science and Technology');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('kbuyers79', 'Julina', 'Dot', 'jdot1p@answers.com', 'Albania', 'Epoka University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('eewell7a', 'Constanta', 'Sumption', 'csumption1q@microsoft.com', 'Philippines', 'Arellano University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('sbithany7b', 'Free', 'Sherewood', 'fsherewood1r@uiuc.edu', 'Afghanistan', 'Kabul Medical University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('dgoodlake7c', 'Elia', 'Krale', 'ekrale1s@qq.com', 'Thailand', 'Eastern Asia University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('cferretti7d', 'Iago', 'Wilce', 'iwilce1t@bloglines.com', 'Indonesia', 'Universitas Bojonegoro');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('preeds7e', 'Gordy', 'Ziehm', 'gziehm1u@list-manage.com', 'Estonia', 'University of Tartu');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('rrickets7f', 'Catlee', 'Pagin', 'cpagin1v@cnn.com', 'Iraq', 'Ishik University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('rfarncombe7g', 'Marne', 'Shalloe', 'mshalloe1w@51.la', 'Sweden', 'Växjö University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('imechan7h', 'Oralie', 'Wodeland', 'owodeland1x@squidoo.com', 'Ukraine', 'KROK Economics and Law University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('rtomei7i', 'Thaxter', 'Bownd', 'tbownd1y@utexas.edu', 'China', 'Xinjiang University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('cmarriott7j', 'Carolann', 'Packington', 'cpackington1z@e-recht24.de', 'Panama', 'Universidad de Panamá');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('skibbe7k', 'Bartel', 'Teggart', 'bteggart20@go.com', 'China', 'Northeast University at Qinhuangdao Campus');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('bmoodie7l', 'Jacquenetta', 'Keightley', 'jkeightley21@shareasale.com', 'Philippines', 'Capitol University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('hsheddan7m', 'Emogene', 'Blois', 'eblois22@wordpress.org', 'Morocco', 'Université Mohammed V - Souissi');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('esleaford7n', 'Goldi', 'Opfer', 'gopfer23@tamu.edu', 'Indonesia', 'Universitas Pakuan');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('gkwietek7o', 'Doll', 'Downey', 'ddowney24@ft.com', 'Indonesia', 'Politeknik Negeri Semarang');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('croskeilly7p', 'Akim', 'Shipston', 'ashipston25@google.de', 'Armenia', 'Yerevan State University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('amacparlan7q', 'Pauli', 'Allbon', 'pallbon26@hud.gov', 'China', 'Southwest Jiaotong University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('rkeys7r', 'Em', 'Orr', 'eorr27@marketwatch.com', 'France', 'Ecole des Hautes Etudes Commerciales');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('vkleine7s', 'Kimmie', 'Knapper', 'kknapper28@vistaprint.com', 'China', 'Chongqing Medical University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('abroseke7t', 'Ricardo', 'Steely', 'rsteely29@howstuffworks.com', 'Brazil', 'Universidade Estadual de Feira de Santana');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('awilbraham7u', 'Goldia', 'Weinham', 'gweinham2a@w3.org', 'Vietnam', 'Ho Chi Minh City University of Social Sciences and Humanities');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('cfabler7v', 'Elle', 'Rawcliff', 'erawcliff2b@elegantthemes.com', 'China', '4th Military Medical University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('bhamshaw7w', 'Darryl', 'Vaisey', 'dvaisey2c@nsw.gov.au', 'Bhutan', 'Royal University of Bhutan');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('vbrahams7x', 'Brandie', 'Verring', 'bverring2d@baidu.com', 'Canada', 'University College of the Fraser Valley');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('mtunsley7y', 'Taylor', 'Houtbie', 'thoutbie2e@moonfruit.com', 'United States', 'Reformed Bible College');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('dfleg7z', 'Joyan', 'Philippsohn', 'jphilippsohn2f@accuweather.com', 'China', 'Hunan Normal University');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('dyarker80', 'Aldis', 'Walford', 'awalford2g@nsw.gov.au', 'Japan', 'Kunitachi College of Music');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('rdeniset81', 'Danyelle', 'Scough', 'dscough2h@discuz.net', 'Portugal', 'Escola Superior de Hotelaria e Turismo do Estoril');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('aerrington82', 'Marven', 'Tivers', 'mtivers2i@comsenz.com', 'Reunion', 'Université de la Reunion');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('candreini83', 'Blayne', 'Weldon', 'bweldon2j@dmoz.org', 'Indonesia', 'Universitas Methodist Indonesia');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('vrudman84', 'Helene', 'Crystal', 'hcrystal2k@wix.com', 'Indonesia', 'Universitas Katolik Widya Karya');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('dalway85', 'Ulises', 'Swash', 'uswash2l@virginia.edu', 'United States', 'University of California, San Francisco');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('dbrazener86', 'Berna', 'Matthias', 'bmatthias2m@mozilla.com', 'Laos', 'Soutsaka Institute of management and Technology');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('lfashion87', 'Ad', 'McCormack', 'amccormack2n@biblegateway.com', 'Czech Republic', 'Technical University of Mining and Metallurgy Ostrava');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('konraet88', 'Yves', 'Ojeda', 'yojeda2o@smh.com.au', 'China', 'Tibet University of Nationalities');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('scarnegie89', 'Eve', 'Crystal', 'ecrystal2p@4shared.com', 'Argentina', 'Universidad Nacional de La Pampa');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('creaney8a', 'Marcie', 'Treffry', 'mtreffry2q@state.gov', 'Palestinian Territory', 'University College of Applied Sciences');
insert into Student (Spotify_username, first_name, last_name, email_atschool, country_school, name_school) values ('rpinilla8b', 'Joelie', 'Davenell', 'jdavenell2r@kickstarter.com', 'Indonesia', 'Politeknik Negeri Malang');
