create table User_Data (
	Spotify_username VARCHAR(50),
	Real_name VARCHAR(50),
	Email_address VARCHAR(50),
	Country VARCHAR(50),
	Date_of_Birth DATE,
	Gender VARCHAR(50)
);
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('knoriega0', 'Kacey Noriega', 'knoriega0@soundcloud.com', 'Brazil', '1988-10-11', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('dphilipsohn1', 'Dene Philipsohn', 'dphilipsohn1@cbslocal.com', 'United States', '1983-08-28', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('aleythley2', 'Avis Leythley', 'aleythley2@google.pl', 'Angola', '2002-06-01', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('lmattin3', 'Loren Mattin', 'lmattin3@google.nl', 'China', '1993-01-31', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('sprebble4', 'Sharron Prebble', 'sprebble4@taobao.com', 'Indonesia', '1992-12-14', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('pvasiljevic5', 'Port Vasiljevic', 'pvasiljevic5@addtoany.com', 'China', '1999-11-17', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('bmilmore6', 'Becky Milmore', 'bmilmore6@pbs.org', 'Brazil', '1993-07-02', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('lfipp7', 'Lindie Fipp', 'lfipp7@ezinearticles.com', 'China', '2002-02-24', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('csilver8', 'Cecelia Silver', 'csilver8@plala.or.jp', 'Indonesia', '1989-07-10', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('gshmyr9', 'Gilda Shmyr', 'gshmyr9@smh.com.au', 'Indonesia', '1987-07-16', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('vbohikea', 'Valentina Bohike', 'vbohikea@dyndns.org', 'China', '1991-03-02', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('besselinb', 'Berti Esselin', 'besselinb@constantcontact.com', 'Austria', '1995-11-20', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('reulerc', 'Reggis Euler', 'reulerc@blog.com', 'Indonesia', '1980-11-27', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('esalvind', 'Evey Salvin', 'esalvind@stumbleupon.com', 'Russia', '1984-11-26', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('lseyfferte', 'Lilli Seyffert', 'lseyfferte@drupal.org', 'South Korea', '1994-06-06', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('dpidcockf', 'Dorothea Pidcock', 'dpidcockf@soundcloud.com', 'Portugal', '1983-02-18', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('sbenfordg', 'Saree Benford', 'sbenfordg@census.gov', 'Greece', '1985-06-19', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('rcaudrelierh', 'Reggie Caudrelier', 'rcaudrelierh@msu.edu', 'Mexico', '1988-07-01', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('graymenti', 'Georas Rayment', 'graymenti@constantcontact.com', 'Canada', '2002-02-03', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('itrevertonj', 'Ingaborg Treverton', 'itrevertonj@opera.com', 'Albania', '1986-09-04', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('kmcgougank', 'Kitti McGougan', 'kmcgougank@macromedia.com', 'Russia', '1999-09-12', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('bfilshinl', 'Bendix Filshin', 'bfilshinl@typepad.com', 'Malaysia', '1981-12-21', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('rdallossom', 'Russ Dallosso', 'rdallossom@yahoo.co.jp', 'Indonesia', '1986-03-22', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('aswetlandn', 'Ash Swetland', 'aswetlandn@apache.org', 'Portugal', '1984-09-24', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('wbattero', 'Willy Batter', 'wbattero@nhs.uk', 'Pakistan', '1994-12-24', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('fdilonp', 'Feliza Dilon', 'fdilonp@psu.edu', 'China', '1994-07-13', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('pwareq', 'Padgett Ware', 'pwareq@amazon.com', 'France', '1983-07-06', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('cmacbainr', 'Caterina MacBain', 'cmacbainr@multiply.com', 'Russia', '1991-03-04', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('cdumberells', 'Cob Dumberell', 'cdumberells@pagesperso-orange.fr', 'Portugal', '1985-12-30', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('mgrinovt', 'Marcos Grinov', 'mgrinovt@amazon.de', 'Czech Republic', '2000-12-30', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('clittericku', 'Christa Litterick', 'clittericku@sogou.com', 'Poland', '1981-04-18', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('dwilkennsonv', 'Dale Wilkennson', 'dwilkennsonv@bluehost.com', 'China', '1994-04-01', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('bhuntingdonw', 'Bria Huntingdon', 'bhuntingdonw@tuttocitta.it', 'United States', '1981-02-03', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('srehmex', 'Sammie Rehme', 'srehmex@shinystat.com', 'South Africa', '1995-07-04', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('ystuckfordy', 'Yorker Stuckford', 'ystuckfordy@multiply.com', 'Russia', '1984-01-22', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('pwardroperz', 'Puff Wardroper', 'pwardroperz@t.co', 'Brazil', '1982-05-25', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('bbazell10', 'Bernadina Bazell', 'bbazell10@cdc.gov', 'China', '1983-11-18', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('mleatt11', 'Mirabelle Leatt', 'mleatt11@diigo.com', 'Indonesia', '1996-02-11', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('plodin12', 'Price Lodin', 'plodin12@jugem.jp', 'Russia', '1986-02-02', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('pbalfre13', 'Peria Balfre', 'pbalfre13@thetimes.co.uk', 'Brazil', '1987-04-14', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('lbraune14', 'Lazaro Braune', 'lbraune14@unesco.org', 'South Korea', '1988-01-03', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('lmeadley15', 'Lionello Meadley', 'lmeadley15@zimbio.com', 'Indonesia', '1993-01-12', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('kjoscelyne16', 'Kevon Joscelyne', 'kjoscelyne16@slate.com', 'Ukraine', '1995-09-29', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('ileithharvey17', 'Ives Leith-Harvey', 'ileithharvey17@creativecommons.org', 'Mongolia', '2000-02-14', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('baldis18', 'Beatriz Aldis', 'baldis18@marketwatch.com', 'Greece', '2001-03-22', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('nbrian19', 'Nessi Brian', 'nbrian19@google.ca', 'Georgia', '1988-06-02', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('mgover1a', 'Merv Gover', 'mgover1a@abc.net.au', 'Lithuania', '1991-09-01', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('strahar1b', 'Sutton Trahar', 'strahar1b@ft.com', 'Canada', '1992-03-05', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('flaffoleylane1c', 'Finlay Laffoley-Lane', 'flaffoleylane1c@ycombinator.com', 'China', '1990-11-08', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('jmonson1d', 'Jackelyn Monson', 'jmonson1d@state.tx.us', 'China', '1990-11-10', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('oharries1e', 'Onfre Harries', 'oharries1e@creativecommons.org', 'Philippines', '1981-08-04', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('kbeton1f', 'Karna Beton', 'kbeton1f@g.co', 'Russia', '2000-04-14', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('lmetzke1g', 'Lonnie Metzke', 'lmetzke1g@house.gov', 'Iran', '1988-05-18', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('dgallamore1h', 'Dori Gallamore', 'dgallamore1h@nba.com', 'China', '2002-10-15', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('gcratchley1i', 'Garfield Cratchley', 'gcratchley1i@techcrunch.com', 'Colombia', '1999-05-30', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('rrobeiro1j', 'Rochester Robeiro', 'rrobeiro1j@ucoz.ru', 'Indonesia', '1996-02-19', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('fcurson1k', 'Fabien Curson', 'fcurson1k@wordpress.com', 'Indonesia', '1990-02-06', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('jrudiger1l', 'Jennine Rudiger', 'jrudiger1l@elpais.com', 'Brazil', '1985-09-19', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('qbootland1m', 'Quinton Bootland', 'qbootland1m@amazon.com', 'China', '2002-11-05', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('pcossam1n', 'Peg Cossam', 'pcossam1n@discuz.net', 'Chile', '1990-04-03', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('aickeringill1o', 'Aymer Ickeringill', 'aickeringill1o@cmu.edu', 'Russia', '2002-02-27', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('ecoggin1p', 'Elfie Coggin', 'ecoggin1p@nytimes.com', 'Colombia', '2002-01-09', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('wmatiewe1q', 'Willem Matiewe', 'wmatiewe1q@wix.com', 'Canada', '2001-06-28', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('froly1r', 'Florence Roly', 'froly1r@themeforest.net', 'Ukraine', '1981-09-30', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('cwardlow1s', 'Crawford Wardlow', 'cwardlow1s@last.fm', 'Indonesia', '2002-06-06', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('gsysland1t', 'Gustavo Sysland', 'gsysland1t@moonfruit.com', 'Saint Martin', '2001-05-19', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('rrouby1u', 'Rolph Rouby', 'rrouby1u@zdnet.com', 'Indonesia', '1994-02-19', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('kduhig1v', 'Katrinka Duhig', 'kduhig1v@naver.com', 'Nicaragua', '1990-09-05', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('ryakolev1w', 'Renato Yakolev', 'ryakolev1w@sourceforge.net', 'Tajikistan', '1981-06-30', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('ibewick1x', 'Ives Bewick', 'ibewick1x@ca.gov', 'Thailand', '2000-09-26', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('neouzan1y', 'Nadean Eouzan', 'neouzan1y@miibeian.gov.cn', 'Canada', '1988-05-11', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('ldeakan1z', 'Ludovico Deakan', 'ldeakan1z@soup.io', 'Philippines', '1986-06-24', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('yboome20', 'Yuma Boome', 'yboome20@howstuffworks.com', 'Portugal', '1987-09-19', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('aredferne21', 'Andrus Redferne', 'aredferne21@yelp.com', 'Philippines', '1989-03-05', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('ptoomer22', 'Peirce Toomer', 'ptoomer22@bing.com', 'Brazil', '1984-09-01', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('cshadfourth23', 'Clementius Shadfourth', 'cshadfourth23@is.gd', 'China', '1992-01-05', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('hcicchetto24', 'Hadlee Cicchetto', 'hcicchetto24@mozilla.org', 'Mongolia', '1984-10-06', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('sdalbey25', 'Samson Dalbey', 'sdalbey25@prnewswire.com', 'Norway', '1994-03-08', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('sslater26', 'Shanta Slater', 'sslater26@netlog.com', 'Iran', '1981-06-07', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('lbusk27', 'Lyn Busk', 'lbusk27@php.net', 'Tunisia', '1997-12-07', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('bbasso28', 'Bevon Basso', 'bbasso28@jiathis.com', 'Czech Republic', '1981-05-15', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('ecossington29', 'Eward Cossington', 'ecossington29@alibaba.com', 'Indonesia', '1996-03-15', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('twearn2a', 'Tiffanie Wearn', 'twearn2a@cdbaby.com', 'Poland', '1998-04-05', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('gbullman2b', 'Gustave Bullman', 'gbullman2b@1688.com', 'Philippines', '1989-07-19', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('aburling2c', 'Abe Burling', 'aburling2c@guardian.co.uk', 'Indonesia', '1997-05-16', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('dhogbourne2d', 'Drew Hogbourne', 'dhogbourne2d@fema.gov', 'Netherlands', '1995-07-26', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('aruspine2e', 'Arlen Ruspine', 'aruspine2e@imgur.com', 'Mexico', '2000-11-20', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('jevason2f', 'Janka Evason', 'jevason2f@ucoz.ru', 'Iran', '1991-09-20', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('dslad2g', 'Dev Slad', 'dslad2g@so-net.ne.jp', 'Indonesia', '1987-09-22', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('dmyers2h', 'Dalenna Myers', 'dmyers2h@nifty.com', 'Indonesia', '2000-11-16', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('kmilksop2i', 'Kiley Milksop', 'kmilksop2i@tripod.com', 'Estonia', '1999-01-07', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('lbunclark2j', 'Leopold Bunclark', 'lbunclark2j@time.com', 'Philippines', '1983-05-30', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('claurenzi2k', 'Corrinne Laurenzi', 'claurenzi2k@vinaora.com', 'Poland', '1982-12-03', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('dplaister2l', 'Dre Plaister', 'dplaister2l@google.pl', 'China', '1994-07-11', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('rsnape2m', 'Ronnica Snape', 'rsnape2m@storify.com', 'China', '1982-09-15', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('smatterson2n', 'Suzy Matterson', 'smatterson2n@cnbc.com', 'Serbia', '1992-01-24', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('dmcanalley2o', 'Dieter McAnalley', 'dmcanalley2o@dyndns.org', 'Indonesia', '2000-12-09', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('ekaines2p', 'Elmo Kaines', 'ekaines2p@unblog.fr', 'China', '1985-06-23', 'Male');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('dpeizer2q', 'Delly Peizer', 'dpeizer2q@trellian.com', 'Afghanistan', '1987-01-05', 'Female');
insert into User_Data (Spotify_username, Real_name, Email_address, Country, Date_of_Birth, Gender) values ('whilland2r', 'Weider Hilland', 'whilland2r@artisteer.com', 'China', '1995-07-24', 'Male');
